// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlc

import (
	"context"
)

const databaseHealth = `-- name: DatabaseHealth :one
SELECT 1::integer AS value
`

func (q *Queries) DatabaseHealth(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, databaseHealth)
	var value int32
	err := row.Scan(&value)
	return value, err
}
