import { describe, expect, it, vi } from 'vitest'
import { createTranslation, getTranslation, patchTranslation } from './translations'

const workspace = { translationId:'10000000-0000-4000-8000-000000000001', revision:1, lifecycle:'DRAFT', targetLanguage:'es', source:{courseId:'20000000-0000-4000-8000-000000000001',courseVersionId:'30000000-0000-4000-8000-000000000001',version:'1.0.0',language:'en'}, course:{title:{source:'Source',translated:null,state:'UNTRANSLATED'},description:{source:'Description',translated:'',state:'TRANSLATED'},learningObjectives:[]},modules:[],assessments:[],completeness:{totalTranslatableFields:2,translatedFields:1,untranslatedFields:1,complete:false} }
describe('translations client',()=>{
  it('rejects malformed workspace responses instead of partially rendering them',async()=>{await expect(getTranslation('10000000-0000-4000-8000-000000000001',{request:vi.fn().mockResolvedValue({translationId:'x'})} as never)).rejects.toThrow('Invalid Translation response')})
  it('preserves explicit empty and null override values in typed PATCH requests',async()=>{const request=vi.fn().mockResolvedValue({translationId:'10000000-0000-4000-8000-000000000001',targetLanguage:'es',lifecycle:'DRAFT',revision:2,completeness:workspace.completeness});const client={request};await patchTranslation(workspace.translationId,1,[{target:'COURSE',field:'title',translated:''},{target:'COURSE',field:'description',translated:null}],client as never);const [,options]=request.mock.calls[0];expect(JSON.parse(options.body)).toEqual({expectedRevision:1,changes:[{target:'COURSE',field:'title',translated:''},{target:'COURSE',field:'description',translated:null}]})})
  it('posts only the target language during creation',async()=>{const request=vi.fn().mockResolvedValue({translationId:workspace.translationId,revision:1});await createTranslation(workspace.source.courseId,workspace.source.version,'es',{request} as never);expect(JSON.parse(request.mock.calls[0][1].body)).toEqual({targetLanguage:'es'})})
})
