// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses.course (slug)
VALUES ($1)
RETURNING id, slug, created_at
`

func (q *Queries) CreateCourse(ctx context.Context, slug string) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, createCourse, slug)
	var i CoursesCourse
	err := row.Scan(&i.ID, &i.Slug, &i.CreatedAt)
	return i, err
}

const createCourseVersion = `-- name: CreateCourseVersion :one
INSERT INTO courses.course_version (
    course_id, version, status, title, description, learning_objectives,
    source_language, changelog, license_kind, license_identifier,
    license_display_name, license_url, license_custom_text, attribution, published_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
`

type CreateCourseVersionParams struct {
	CourseID           pgtype.UUID
	Version            string
	Status             string
	Title              string
	Description        string
	LearningObjectives []byte
	SourceLanguage     string
	Changelog          string
	LicenseKind        string
	LicenseIdentifier  pgtype.Text
	LicenseDisplayName string
	LicenseUrl         pgtype.Text
	LicenseCustomText  pgtype.Text
	Attribution        []byte
	PublishedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCourseVersion(ctx context.Context, arg CreateCourseVersionParams) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, createCourseVersion,
		arg.CourseID,
		arg.Version,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.SourceLanguage,
		arg.Changelog,
		arg.LicenseKind,
		arg.LicenseIdentifier,
		arg.LicenseDisplayName,
		arg.LicenseUrl,
		arg.LicenseCustomText,
		arg.Attribution,
		arg.PublishedAt,
	)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, slug, created_at
FROM courses.course
WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id pgtype.UUID) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i CoursesCourse
	err := row.Scan(&i.ID, &i.Slug, &i.CreatedAt)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, created_at
FROM courses.course
WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i CoursesCourse
	err := row.Scan(&i.ID, &i.Slug, &i.CreatedAt)
	return i, err
}

const getCourseVersion = `-- name: GetCourseVersion :one
SELECT id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
FROM courses.course_version
WHERE id = $1
`

func (q *Queries) GetCourseVersion(ctx context.Context, id pgtype.UUID) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersion, id)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getCourseVersionByCourseAndVersion = `-- name: GetCourseVersionByCourseAndVersion :one
SELECT id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
FROM courses.course_version
WHERE course_id = $1 AND version = $2
`

type GetCourseVersionByCourseAndVersionParams struct {
	CourseID pgtype.UUID
	Version  string
}

func (q *Queries) GetCourseVersionByCourseAndVersion(ctx context.Context, arg GetCourseVersionByCourseAndVersionParams) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersionByCourseAndVersion, arg.CourseID, arg.Version)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listCourseVersions = `-- name: ListCourseVersions :many
SELECT id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
FROM courses.course_version
WHERE course_id = $1
ORDER BY version_major DESC, version_minor DESC, version_patch DESC, id DESC
`

func (q *Queries) ListCourseVersions(ctx context.Context, courseID pgtype.UUID) ([]CoursesCourseVersion, error) {
	rows, err := q.db.Query(ctx, listCourseVersions, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesCourseVersion
	for rows.Next() {
		var i CoursesCourseVersion
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Version,
			&i.VersionMajor,
			&i.VersionMinor,
			&i.VersionPatch,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.SourceLanguage,
			&i.Changelog,
			&i.LicenseKind,
			&i.LicenseIdentifier,
			&i.LicenseDisplayName,
			&i.LicenseUrl,
			&i.LicenseCustomText,
			&i.Attribution,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, created_at
FROM courses.course
ORDER BY slug ASC, id ASC
`

func (q *Queries) ListCourses(ctx context.Context) ([]CoursesCourse, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesCourse
	for rows.Next() {
		var i CoursesCourse
		if err := rows.Scan(&i.ID, &i.Slug, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionCourseVersionStatus = `-- name: TransitionCourseVersionStatus :one
UPDATE courses.course_version
SET status = $3
WHERE id = $1 AND status = $2
RETURNING id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
`

type TransitionCourseVersionStatusParams struct {
	ID       pgtype.UUID
	Status   string
	Status_2 string
}

func (q *Queries) TransitionCourseVersionStatus(ctx context.Context, arg TransitionCourseVersionStatusParams) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, transitionCourseVersionStatus, arg.ID, arg.Status, arg.Status_2)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}
