// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLatestPublishedCourses = `-- name: CountLatestPublishedCourses :one
WITH latest AS (
    SELECT DISTINCT ON (version.course_id) version.course_id, version.source_language
    FROM courses.course_version AS version
    JOIN courses.course_version_publication_provenance AS provenance
        ON provenance.course_version_id = version.id
    WHERE version.status = 'PUBLISHED'
    ORDER BY version.course_id, version.version_major DESC, version.version_minor DESC, version.version_patch DESC, version.id DESC
)
SELECT count(*)
FROM latest
WHERE ($1::text IS NULL OR source_language = $1::text)
`

func (q *Queries) CountLatestPublishedCourses(ctx context.Context, language pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countLatestPublishedCourses, language)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses.course (slug)
VALUES ($1)
RETURNING id, slug, created_at
`

func (q *Queries) CreateCourse(ctx context.Context, slug string) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, createCourse, slug)
	var i CoursesCourse
	err := row.Scan(&i.ID, &i.Slug, &i.CreatedAt)
	return i, err
}

const createCourseVersion = `-- name: CreateCourseVersion :one
INSERT INTO courses.course_version (
    course_id, version, status, title, description, learning_objectives,
    source_language, changelog, license_kind, license_identifier,
    license_display_name, license_url, license_custom_text, attribution, published_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
`

type CreateCourseVersionParams struct {
	CourseID           pgtype.UUID
	Version            string
	Status             string
	Title              string
	Description        string
	LearningObjectives []byte
	SourceLanguage     string
	Changelog          string
	LicenseKind        string
	LicenseIdentifier  pgtype.Text
	LicenseDisplayName string
	LicenseUrl         pgtype.Text
	LicenseCustomText  pgtype.Text
	Attribution        []byte
	PublishedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCourseVersion(ctx context.Context, arg CreateCourseVersionParams) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, createCourseVersion,
		arg.CourseID,
		arg.Version,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.SourceLanguage,
		arg.Changelog,
		arg.LicenseKind,
		arg.LicenseIdentifier,
		arg.LicenseDisplayName,
		arg.LicenseUrl,
		arg.LicenseCustomText,
		arg.Attribution,
		arg.PublishedAt,
	)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createCourseVersionPublicationProvenance = `-- name: CreateCourseVersionPublicationProvenance :one
INSERT INTO courses.course_version_publication_provenance (
    course_version_id, review_id, review_revision, draft_id, draft_revision,
    snapshot_schema_version, submitted_by_user_id, submitted_at,
    approved_by_user_id, approved_at, published_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING course_version_id, review_id, review_revision, draft_id, draft_revision, snapshot_schema_version, submitted_by_user_id, submitted_at, approved_by_user_id, approved_at, published_by_user_id
`

type CreateCourseVersionPublicationProvenanceParams struct {
	CourseVersionID       pgtype.UUID
	ReviewID              pgtype.UUID
	ReviewRevision        int64
	DraftID               pgtype.UUID
	DraftRevision         int64
	SnapshotSchemaVersion int32
	SubmittedByUserID     pgtype.UUID
	SubmittedAt           pgtype.Timestamptz
	ApprovedByUserID      pgtype.UUID
	ApprovedAt            pgtype.Timestamptz
	PublishedByUserID     pgtype.UUID
}

func (q *Queries) CreateCourseVersionPublicationProvenance(ctx context.Context, arg CreateCourseVersionPublicationProvenanceParams) (CoursesCourseVersionPublicationProvenance, error) {
	row := q.db.QueryRow(ctx, createCourseVersionPublicationProvenance,
		arg.CourseVersionID,
		arg.ReviewID,
		arg.ReviewRevision,
		arg.DraftID,
		arg.DraftRevision,
		arg.SnapshotSchemaVersion,
		arg.SubmittedByUserID,
		arg.SubmittedAt,
		arg.ApprovedByUserID,
		arg.ApprovedAt,
		arg.PublishedByUserID,
	)
	var i CoursesCourseVersionPublicationProvenance
	err := row.Scan(
		&i.CourseVersionID,
		&i.ReviewID,
		&i.ReviewRevision,
		&i.DraftID,
		&i.DraftRevision,
		&i.SnapshotSchemaVersion,
		&i.SubmittedByUserID,
		&i.SubmittedAt,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.PublishedByUserID,
	)
	return i, err
}

const createImmutableCourseVersionLesson = `-- name: CreateImmutableCourseVersionLesson :one
INSERT INTO courses.lesson (
    course_version_id, module_id, source_lesson_id, stable_key, title,
    description, learning_objectives, estimated_duration_minutes, position, content
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, course_version_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, created_at, content, source_lesson_id
`

type CreateImmutableCourseVersionLessonParams struct {
	CourseVersionID          pgtype.UUID
	ModuleID                 pgtype.UUID
	SourceLessonID           pgtype.UUID
	StableKey                string
	Title                    string
	Description              string
	LearningObjectives       []byte
	EstimatedDurationMinutes pgtype.Int4
	Position                 int32
	Content                  []byte
}

func (q *Queries) CreateImmutableCourseVersionLesson(ctx context.Context, arg CreateImmutableCourseVersionLessonParams) (CoursesLesson, error) {
	row := q.db.QueryRow(ctx, createImmutableCourseVersionLesson,
		arg.CourseVersionID,
		arg.ModuleID,
		arg.SourceLessonID,
		arg.StableKey,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.EstimatedDurationMinutes,
		arg.Position,
		arg.Content,
	)
	var i CoursesLesson
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.CreatedAt,
		&i.Content,
		&i.SourceLessonID,
	)
	return i, err
}

const createImmutableCourseVersionModule = `-- name: CreateImmutableCourseVersionModule :one
INSERT INTO courses.module (course_version_id, source_module_id, stable_key, title, description, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, course_version_id, stable_key, title, description, position, created_at, source_module_id
`

type CreateImmutableCourseVersionModuleParams struct {
	CourseVersionID pgtype.UUID
	SourceModuleID  pgtype.UUID
	StableKey       string
	Title           string
	Description     string
	Position        int32
}

func (q *Queries) CreateImmutableCourseVersionModule(ctx context.Context, arg CreateImmutableCourseVersionModuleParams) (CoursesModule, error) {
	row := q.db.QueryRow(ctx, createImmutableCourseVersionModule,
		arg.CourseVersionID,
		arg.SourceModuleID,
		arg.StableKey,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i CoursesModule
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.SourceModuleID,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO courses.lesson (
    course_version_id, module_id, stable_key, title, description,
    learning_objectives, estimated_duration_minutes, position, content
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, course_version_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, created_at, content, source_lesson_id
`

type CreateLessonParams struct {
	CourseVersionID          pgtype.UUID
	ModuleID                 pgtype.UUID
	StableKey                string
	Title                    string
	Description              string
	LearningObjectives       []byte
	EstimatedDurationMinutes pgtype.Int4
	Position                 int32
	Content                  []byte
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (CoursesLesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.CourseVersionID,
		arg.ModuleID,
		arg.StableKey,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.EstimatedDurationMinutes,
		arg.Position,
		arg.Content,
	)
	var i CoursesLesson
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.CreatedAt,
		&i.Content,
		&i.SourceLessonID,
	)
	return i, err
}

const createLessonPrerequisite = `-- name: CreateLessonPrerequisite :one
INSERT INTO courses.lesson_prerequisite (course_version_id, lesson_id, prerequisite_lesson_id, position)
VALUES ($1, $2, $3, $4)
RETURNING course_version_id, lesson_id, prerequisite_lesson_id, position
`

type CreateLessonPrerequisiteParams struct {
	CourseVersionID      pgtype.UUID
	LessonID             pgtype.UUID
	PrerequisiteLessonID pgtype.UUID
	Position             int32
}

func (q *Queries) CreateLessonPrerequisite(ctx context.Context, arg CreateLessonPrerequisiteParams) (CoursesLessonPrerequisite, error) {
	row := q.db.QueryRow(ctx, createLessonPrerequisite,
		arg.CourseVersionID,
		arg.LessonID,
		arg.PrerequisiteLessonID,
		arg.Position,
	)
	var i CoursesLessonPrerequisite
	err := row.Scan(
		&i.CourseVersionID,
		&i.LessonID,
		&i.PrerequisiteLessonID,
		&i.Position,
	)
	return i, err
}

const createModule = `-- name: CreateModule :one
INSERT INTO courses.module (course_version_id, stable_key, title, description, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_version_id, stable_key, title, description, position, created_at, source_module_id
`

type CreateModuleParams struct {
	CourseVersionID pgtype.UUID
	StableKey       string
	Title           string
	Description     string
	Position        int32
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (CoursesModule, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.CourseVersionID,
		arg.StableKey,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i CoursesModule
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.SourceModuleID,
	)
	return i, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, slug, created_at
FROM courses.course
WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id pgtype.UUID) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i CoursesCourse
	err := row.Scan(&i.ID, &i.Slug, &i.CreatedAt)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, created_at
FROM courses.course
WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (CoursesCourse, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i CoursesCourse
	err := row.Scan(&i.ID, &i.Slug, &i.CreatedAt)
	return i, err
}

const getCourseVersion = `-- name: GetCourseVersion :one
SELECT id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
FROM courses.course_version
WHERE id = $1
`

func (q *Queries) GetCourseVersion(ctx context.Context, id pgtype.UUID) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersion, id)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getCourseVersionByCourseAndVersion = `-- name: GetCourseVersionByCourseAndVersion :one
SELECT id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
FROM courses.course_version
WHERE course_id = $1 AND version = $2
`

type GetCourseVersionByCourseAndVersionParams struct {
	CourseID pgtype.UUID
	Version  string
}

func (q *Queries) GetCourseVersionByCourseAndVersion(ctx context.Context, arg GetCourseVersionByCourseAndVersionParams) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, getCourseVersionByCourseAndVersion, arg.CourseID, arg.Version)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getCourseVersionIDByReviewID = `-- name: GetCourseVersionIDByReviewID :one
SELECT course_version_id
FROM courses.course_version_publication_provenance
WHERE review_id = $1
`

func (q *Queries) GetCourseVersionIDByReviewID(ctx context.Context, reviewID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCourseVersionIDByReviewID, reviewID)
	var course_version_id pgtype.UUID
	err := row.Scan(&course_version_id)
	return course_version_id, err
}

const getCourseVersionPublicationProvenance = `-- name: GetCourseVersionPublicationProvenance :one
SELECT course_version_id, review_id, review_revision, draft_id, draft_revision, snapshot_schema_version, submitted_by_user_id, submitted_at, approved_by_user_id, approved_at, published_by_user_id
FROM courses.course_version_publication_provenance
WHERE course_version_id = $1
`

func (q *Queries) GetCourseVersionPublicationProvenance(ctx context.Context, courseVersionID pgtype.UUID) (CoursesCourseVersionPublicationProvenance, error) {
	row := q.db.QueryRow(ctx, getCourseVersionPublicationProvenance, courseVersionID)
	var i CoursesCourseVersionPublicationProvenance
	err := row.Scan(
		&i.CourseVersionID,
		&i.ReviewID,
		&i.ReviewRevision,
		&i.DraftID,
		&i.DraftRevision,
		&i.SnapshotSchemaVersion,
		&i.SubmittedByUserID,
		&i.SubmittedAt,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.PublishedByUserID,
	)
	return i, err
}

const getLatestPublishedCourseVersionID = `-- name: GetLatestPublishedCourseVersionID :one
SELECT id
FROM courses.course_version
WHERE course_id = $1 AND status = 'PUBLISHED'
ORDER BY version_major DESC, version_minor DESC, version_patch DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestPublishedCourseVersionID(ctx context.Context, courseID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestPublishedCourseVersionID, courseID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLesson = `-- name: GetLesson :one
SELECT id, course_version_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, created_at, content, source_lesson_id
FROM courses.lesson
WHERE id = $1
`

func (q *Queries) GetLesson(ctx context.Context, id pgtype.UUID) (CoursesLesson, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i CoursesLesson
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.CreatedAt,
		&i.Content,
		&i.SourceLessonID,
	)
	return i, err
}

const getLessonByCourseVersionAndKey = `-- name: GetLessonByCourseVersionAndKey :one
SELECT id, course_version_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, created_at, content, source_lesson_id
FROM courses.lesson
WHERE course_version_id = $1 AND stable_key = $2
`

type GetLessonByCourseVersionAndKeyParams struct {
	CourseVersionID pgtype.UUID
	StableKey       string
}

func (q *Queries) GetLessonByCourseVersionAndKey(ctx context.Context, arg GetLessonByCourseVersionAndKeyParams) (CoursesLesson, error) {
	row := q.db.QueryRow(ctx, getLessonByCourseVersionAndKey, arg.CourseVersionID, arg.StableKey)
	var i CoursesLesson
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.CreatedAt,
		&i.Content,
		&i.SourceLessonID,
	)
	return i, err
}

const getModule = `-- name: GetModule :one
SELECT id, course_version_id, stable_key, title, description, position, created_at, source_module_id
FROM courses.module
WHERE id = $1
`

func (q *Queries) GetModule(ctx context.Context, id pgtype.UUID) (CoursesModule, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i CoursesModule
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.SourceModuleID,
	)
	return i, err
}

const getModuleByCourseVersionAndKey = `-- name: GetModuleByCourseVersionAndKey :one
SELECT id, course_version_id, stable_key, title, description, position, created_at, source_module_id
FROM courses.module
WHERE course_version_id = $1 AND stable_key = $2
`

type GetModuleByCourseVersionAndKeyParams struct {
	CourseVersionID pgtype.UUID
	StableKey       string
}

func (q *Queries) GetModuleByCourseVersionAndKey(ctx context.Context, arg GetModuleByCourseVersionAndKeyParams) (CoursesModule, error) {
	row := q.db.QueryRow(ctx, getModuleByCourseVersionAndKey, arg.CourseVersionID, arg.StableKey)
	var i CoursesModule
	err := row.Scan(
		&i.ID,
		&i.CourseVersionID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.SourceModuleID,
	)
	return i, err
}

const getPublishedCourseVersionIDByCourseAndVersion = `-- name: GetPublishedCourseVersionIDByCourseAndVersion :one
SELECT id
FROM courses.course_version
WHERE course_id = $1 AND version = $2 AND status = 'PUBLISHED'
`

type GetPublishedCourseVersionIDByCourseAndVersionParams struct {
	CourseID pgtype.UUID
	Version  string
}

func (q *Queries) GetPublishedCourseVersionIDByCourseAndVersion(ctx context.Context, arg GetPublishedCourseVersionIDByCourseAndVersionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPublishedCourseVersionIDByCourseAndVersion, arg.CourseID, arg.Version)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCourseVersions = `-- name: ListCourseVersions :many
SELECT id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
FROM courses.course_version
WHERE course_id = $1
ORDER BY version_major DESC, version_minor DESC, version_patch DESC, id DESC
`

func (q *Queries) ListCourseVersions(ctx context.Context, courseID pgtype.UUID) ([]CoursesCourseVersion, error) {
	rows, err := q.db.Query(ctx, listCourseVersions, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesCourseVersion
	for rows.Next() {
		var i CoursesCourseVersion
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Version,
			&i.VersionMajor,
			&i.VersionMinor,
			&i.VersionPatch,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.SourceLanguage,
			&i.Changelog,
			&i.LicenseKind,
			&i.LicenseIdentifier,
			&i.LicenseDisplayName,
			&i.LicenseUrl,
			&i.LicenseCustomText,
			&i.Attribution,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, created_at
FROM courses.course
ORDER BY slug ASC, id ASC
`

func (q *Queries) ListCourses(ctx context.Context) ([]CoursesCourse, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesCourse
	for rows.Next() {
		var i CoursesCourse
		if err := rows.Scan(&i.ID, &i.Slug, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPublishedCourseVersions = `-- name: ListLatestPublishedCourseVersions :many
WITH latest AS (
    SELECT DISTINCT ON (version.course_id) version.id
    FROM courses.course_version AS version
    JOIN courses.course_version_publication_provenance AS provenance
        ON provenance.course_version_id = version.id
    WHERE version.status = 'PUBLISHED'
    ORDER BY version.course_id, version.version_major DESC, version.version_minor DESC, version.version_patch DESC, version.id DESC
)
SELECT version.id, version.course_id, version.version, version.version_major, version.version_minor, version.version_patch, version.status, version.title, version.description, version.learning_objectives, version.source_language, version.changelog, version.license_kind, version.license_identifier, version.license_display_name, version.license_url, version.license_custom_text, version.attribution, version.created_at, version.published_at
FROM courses.course_version AS version
JOIN latest ON latest.id = version.id
WHERE ($1::text IS NULL OR version.source_language = $1::text)
ORDER BY version.title ASC, version.course_id ASC
LIMIT $3 OFFSET $2
`

type ListLatestPublishedCourseVersionsParams struct {
	Language pgtype.Text
	Offset   int32
	Limit    int32
}

func (q *Queries) ListLatestPublishedCourseVersions(ctx context.Context, arg ListLatestPublishedCourseVersionsParams) ([]CoursesCourseVersion, error) {
	rows, err := q.db.Query(ctx, listLatestPublishedCourseVersions, arg.Language, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesCourseVersion
	for rows.Next() {
		var i CoursesCourseVersion
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Version,
			&i.VersionMajor,
			&i.VersionMinor,
			&i.VersionPatch,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.SourceLanguage,
			&i.Changelog,
			&i.LicenseKind,
			&i.LicenseIdentifier,
			&i.LicenseDisplayName,
			&i.LicenseUrl,
			&i.LicenseCustomText,
			&i.Attribution,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonPrerequisites = `-- name: ListLessonPrerequisites :many
SELECT
    prerequisite.course_version_id,
    prerequisite.lesson_id,
    prerequisite.prerequisite_lesson_id,
    prerequisite.position,
    target.stable_key AS prerequisite_stable_key
FROM courses.lesson_prerequisite AS prerequisite
JOIN courses.lesson AS target ON target.id = prerequisite.prerequisite_lesson_id
WHERE prerequisite.lesson_id = $1
ORDER BY prerequisite.position ASC, prerequisite.prerequisite_lesson_id ASC
`

type ListLessonPrerequisitesRow struct {
	CourseVersionID       pgtype.UUID
	LessonID              pgtype.UUID
	PrerequisiteLessonID  pgtype.UUID
	Position              int32
	PrerequisiteStableKey string
}

func (q *Queries) ListLessonPrerequisites(ctx context.Context, lessonID pgtype.UUID) ([]ListLessonPrerequisitesRow, error) {
	rows, err := q.db.Query(ctx, listLessonPrerequisites, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonPrerequisitesRow
	for rows.Next() {
		var i ListLessonPrerequisitesRow
		if err := rows.Scan(
			&i.CourseVersionID,
			&i.LessonID,
			&i.PrerequisiteLessonID,
			&i.Position,
			&i.PrerequisiteStableKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonPrerequisitesForCourseVersion = `-- name: ListLessonPrerequisitesForCourseVersion :many
SELECT
    prerequisite.course_version_id,
    prerequisite.lesson_id,
    prerequisite.prerequisite_lesson_id,
    prerequisite.position,
    target.stable_key AS prerequisite_stable_key
FROM courses.lesson_prerequisite AS prerequisite
JOIN courses.lesson AS target ON target.id = prerequisite.prerequisite_lesson_id
WHERE prerequisite.course_version_id = $1
ORDER BY prerequisite.lesson_id ASC, prerequisite.position ASC, prerequisite.prerequisite_lesson_id ASC
`

type ListLessonPrerequisitesForCourseVersionRow struct {
	CourseVersionID       pgtype.UUID
	LessonID              pgtype.UUID
	PrerequisiteLessonID  pgtype.UUID
	Position              int32
	PrerequisiteStableKey string
}

func (q *Queries) ListLessonPrerequisitesForCourseVersion(ctx context.Context, courseVersionID pgtype.UUID) ([]ListLessonPrerequisitesForCourseVersionRow, error) {
	rows, err := q.db.Query(ctx, listLessonPrerequisitesForCourseVersion, courseVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonPrerequisitesForCourseVersionRow
	for rows.Next() {
		var i ListLessonPrerequisitesForCourseVersionRow
		if err := rows.Scan(
			&i.CourseVersionID,
			&i.LessonID,
			&i.PrerequisiteLessonID,
			&i.Position,
			&i.PrerequisiteStableKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonSummariesForCourseVersion = `-- name: ListLessonSummariesForCourseVersion :many
SELECT id, course_version_id, module_id, stable_key, title, description,
       learning_objectives, estimated_duration_minutes, position
FROM courses.lesson
WHERE course_version_id = $1
ORDER BY module_id ASC, position ASC, id ASC
`

type ListLessonSummariesForCourseVersionRow struct {
	ID                       pgtype.UUID
	CourseVersionID          pgtype.UUID
	ModuleID                 pgtype.UUID
	StableKey                string
	Title                    string
	Description              string
	LearningObjectives       []byte
	EstimatedDurationMinutes pgtype.Int4
	Position                 int32
}

func (q *Queries) ListLessonSummariesForCourseVersion(ctx context.Context, courseVersionID pgtype.UUID) ([]ListLessonSummariesForCourseVersionRow, error) {
	rows, err := q.db.Query(ctx, listLessonSummariesForCourseVersion, courseVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonSummariesForCourseVersionRow
	for rows.Next() {
		var i ListLessonSummariesForCourseVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseVersionID,
			&i.ModuleID,
			&i.StableKey,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.EstimatedDurationMinutes,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsForCourseVersion = `-- name: ListLessonsForCourseVersion :many
SELECT id, course_version_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, created_at, content, source_lesson_id
FROM courses.lesson
WHERE course_version_id = $1
ORDER BY module_id ASC, position ASC, id ASC
`

func (q *Queries) ListLessonsForCourseVersion(ctx context.Context, courseVersionID pgtype.UUID) ([]CoursesLesson, error) {
	rows, err := q.db.Query(ctx, listLessonsForCourseVersion, courseVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesLesson
	for rows.Next() {
		var i CoursesLesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseVersionID,
			&i.ModuleID,
			&i.StableKey,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.EstimatedDurationMinutes,
			&i.Position,
			&i.CreatedAt,
			&i.Content,
			&i.SourceLessonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsForModule = `-- name: ListLessonsForModule :many
SELECT id, course_version_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, created_at, content, source_lesson_id
FROM courses.lesson
WHERE module_id = $1
ORDER BY position ASC, id ASC
`

func (q *Queries) ListLessonsForModule(ctx context.Context, moduleID pgtype.UUID) ([]CoursesLesson, error) {
	rows, err := q.db.Query(ctx, listLessonsForModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesLesson
	for rows.Next() {
		var i CoursesLesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseVersionID,
			&i.ModuleID,
			&i.StableKey,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.EstimatedDurationMinutes,
			&i.Position,
			&i.CreatedAt,
			&i.Content,
			&i.SourceLessonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulesForCourseVersion = `-- name: ListModulesForCourseVersion :many
SELECT id, course_version_id, stable_key, title, description, position, created_at, source_module_id
FROM courses.module
WHERE course_version_id = $1
ORDER BY position ASC, id ASC
`

func (q *Queries) ListModulesForCourseVersion(ctx context.Context, courseVersionID pgtype.UUID) ([]CoursesModule, error) {
	rows, err := q.db.Query(ctx, listModulesForCourseVersion, courseVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesModule
	for rows.Next() {
		var i CoursesModule
		if err := rows.Scan(
			&i.ID,
			&i.CourseVersionID,
			&i.StableKey,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.SourceModuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCourseVersions = `-- name: ListPublishedCourseVersions :many
SELECT id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
FROM courses.course_version
WHERE status = 'PUBLISHED'
ORDER BY course_id ASC, version_major DESC, version_minor DESC, version_patch DESC, id DESC
`

func (q *Queries) ListPublishedCourseVersions(ctx context.Context) ([]CoursesCourseVersion, error) {
	rows, err := q.db.Query(ctx, listPublishedCourseVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursesCourseVersion
	for rows.Next() {
		var i CoursesCourseVersion
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Version,
			&i.VersionMajor,
			&i.VersionMinor,
			&i.VersionPatch,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.SourceLanguage,
			&i.Changelog,
			&i.LicenseKind,
			&i.LicenseIdentifier,
			&i.LicenseDisplayName,
			&i.LicenseUrl,
			&i.LicenseCustomText,
			&i.Attribution,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionCourseVersionStatus = `-- name: TransitionCourseVersionStatus :one
UPDATE courses.course_version
SET status = $3
WHERE id = $1 AND status = $2
RETURNING id, course_id, version, version_major, version_minor, version_patch, status, title, description, learning_objectives, source_language, changelog, license_kind, license_identifier, license_display_name, license_url, license_custom_text, attribution, created_at, published_at
`

type TransitionCourseVersionStatusParams struct {
	ID       pgtype.UUID
	Status   string
	Status_2 string
}

func (q *Queries) TransitionCourseVersionStatus(ctx context.Context, arg TransitionCourseVersionStatusParams) (CoursesCourseVersion, error) {
	row := q.db.QueryRow(ctx, transitionCourseVersionStatus, arg.ID, arg.Status, arg.Status_2)
	var i CoursesCourseVersion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Version,
		&i.VersionMajor,
		&i.VersionMinor,
		&i.VersionPatch,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.SourceLanguage,
		&i.Changelog,
		&i.LicenseKind,
		&i.LicenseIdentifier,
		&i.LicenseDisplayName,
		&i.LicenseUrl,
		&i.LicenseCustomText,
		&i.Attribution,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}
