// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoursesCourse struct {
	ID        pgtype.UUID
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type CoursesCourseVersion struct {
	ID                 pgtype.UUID
	CourseID           pgtype.UUID
	Version            string
	VersionMajor       pgtype.Int4
	VersionMinor       pgtype.Int4
	VersionPatch       pgtype.Int4
	Status             string
	Title              string
	Description        string
	LearningObjectives []byte
	SourceLanguage     string
	Changelog          string
	LicenseKind        string
	LicenseIdentifier  pgtype.Text
	LicenseDisplayName string
	LicenseUrl         pgtype.Text
	LicenseCustomText  pgtype.Text
	Attribution        []byte
	CreatedAt          pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
}
