// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments.assessment (owner_draft_id, title, definition, created_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_draft_id, title, revision, definition, created_by_user_id, created_at, updated_at
`

type CreateAssessmentParams struct {
	OwnerDraftID    pgtype.UUID
	Title           string
	Definition      []byte
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (AssessmentsAssessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.OwnerDraftID,
		arg.Title,
		arg.Definition,
		arg.CreatedByUserID,
	)
	var i AssessmentsAssessment
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.Title,
		&i.Revision,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, owner_draft_id, title, revision, definition, created_by_user_id, created_at, updated_at
FROM assessments.assessment
WHERE id = $1
`

func (q *Queries) GetAssessment(ctx context.Context, id pgtype.UUID) (AssessmentsAssessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, id)
	var i AssessmentsAssessment
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.Title,
		&i.Revision,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssessment = `-- name: UpdateAssessment :one
UPDATE assessments.assessment
SET title = $3,
    definition = $4,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1 AND revision = $2
RETURNING id, owner_draft_id, title, revision, definition, created_by_user_id, created_at, updated_at
`

type UpdateAssessmentParams struct {
	ID         pgtype.UUID
	Revision   int64
	Title      string
	Definition []byte
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (AssessmentsAssessment, error) {
	row := q.db.QueryRow(ctx, updateAssessment,
		arg.ID,
		arg.Revision,
		arg.Title,
		arg.Definition,
	)
	var i AssessmentsAssessment
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.Title,
		&i.Revision,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
