// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssessmentSummariesForDraft = `-- name: CountAssessmentSummariesForDraft :one
SELECT count(*)
FROM assessments.assessment
WHERE owner_draft_id = $1
`

func (q *Queries) CountAssessmentSummariesForDraft(ctx context.Context, ownerDraftID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssessmentSummariesForDraft, ownerDraftID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments.assessment (owner_draft_id, title, definition, created_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_draft_id, title, revision, definition, created_by_user_id, created_at, updated_at
`

type CreateAssessmentParams struct {
	OwnerDraftID    pgtype.UUID
	Title           string
	Definition      []byte
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (AssessmentsAssessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.OwnerDraftID,
		arg.Title,
		arg.Definition,
		arg.CreatedByUserID,
	)
	var i AssessmentsAssessment
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.Title,
		&i.Revision,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, owner_draft_id, title, revision, definition, created_by_user_id, created_at, updated_at
FROM assessments.assessment
WHERE id = $1
`

func (q *Queries) GetAssessment(ctx context.Context, id pgtype.UUID) (AssessmentsAssessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, id)
	var i AssessmentsAssessment
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.Title,
		&i.Revision,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssessmentSummariesForDraft = `-- name: ListAssessmentSummariesForDraft :many
SELECT id, title, jsonb_array_length(definition->'questions') AS question_count, revision, updated_at
FROM assessments.assessment
WHERE owner_draft_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAssessmentSummariesForDraftParams struct {
	OwnerDraftID pgtype.UUID
	Limit        int32
	Offset       int32
}

type ListAssessmentSummariesForDraftRow struct {
	ID            pgtype.UUID
	Title         string
	QuestionCount int32
	Revision      int64
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListAssessmentSummariesForDraft(ctx context.Context, arg ListAssessmentSummariesForDraftParams) ([]ListAssessmentSummariesForDraftRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentSummariesForDraft, arg.OwnerDraftID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentSummariesForDraftRow
	for rows.Next() {
		var i ListAssessmentSummariesForDraftRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.QuestionCount,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssessment = `-- name: UpdateAssessment :one
UPDATE assessments.assessment
SET title = $3,
    definition = $4,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1 AND revision = $2
RETURNING id, owner_draft_id, title, revision, definition, created_by_user_id, created_at, updated_at
`

type UpdateAssessmentParams struct {
	ID         pgtype.UUID
	Revision   int64
	Title      string
	Definition []byte
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (AssessmentsAssessment, error) {
	row := q.db.QueryRow(ctx, updateAssessment,
		arg.ID,
		arg.Revision,
		arg.Title,
		arg.Definition,
	)
	var i AssessmentsAssessment
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.Title,
		&i.Revision,
		&i.Definition,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
