// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssessmentAttempt = `-- name: CreateAssessmentAttempt :one
INSERT INTO assessments.assessment_attempt (learner_user_id, course_version_id, assessment_key, responses)
VALUES ($1, $2, $3, $4)
RETURNING id, learner_user_id, course_version_id, assessment_key, state, revision, responses, created_at, updated_at, submitted_at, correct_count, total_count
`

type CreateAssessmentAttemptParams struct {
	LearnerUserID   pgtype.UUID
	CourseVersionID pgtype.UUID
	AssessmentKey   pgtype.UUID
	Responses       []byte
}

func (q *Queries) CreateAssessmentAttempt(ctx context.Context, arg CreateAssessmentAttemptParams) (AssessmentsAssessmentAttempt, error) {
	row := q.db.QueryRow(ctx, createAssessmentAttempt,
		arg.LearnerUserID,
		arg.CourseVersionID,
		arg.AssessmentKey,
		arg.Responses,
	)
	var i AssessmentsAssessmentAttempt
	err := row.Scan(
		&i.ID,
		&i.LearnerUserID,
		&i.CourseVersionID,
		&i.AssessmentKey,
		&i.State,
		&i.Revision,
		&i.Responses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CorrectCount,
		&i.TotalCount,
	)
	return i, err
}

const getAssessmentAttempt = `-- name: GetAssessmentAttempt :one
SELECT id, learner_user_id, course_version_id, assessment_key, state, revision, responses, created_at, updated_at, submitted_at, correct_count, total_count
FROM assessments.assessment_attempt
WHERE id = $1
`

func (q *Queries) GetAssessmentAttempt(ctx context.Context, id pgtype.UUID) (AssessmentsAssessmentAttempt, error) {
	row := q.db.QueryRow(ctx, getAssessmentAttempt, id)
	var i AssessmentsAssessmentAttempt
	err := row.Scan(
		&i.ID,
		&i.LearnerUserID,
		&i.CourseVersionID,
		&i.AssessmentKey,
		&i.State,
		&i.Revision,
		&i.Responses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CorrectCount,
		&i.TotalCount,
	)
	return i, err
}

const submitAssessmentAttempt = `-- name: SubmitAssessmentAttempt :one
UPDATE assessments.assessment_attempt
SET state = 'SUBMITTED',
    submitted_at = $3,
    correct_count = $4,
    total_count = $5,
    revision = revision + 1,
    updated_at = $3
WHERE id = $1 AND revision = $2 AND state = 'IN_PROGRESS'
RETURNING id, learner_user_id, course_version_id, assessment_key, state, revision, responses, created_at, updated_at, submitted_at, correct_count, total_count
`

type SubmitAssessmentAttemptParams struct {
	ID           pgtype.UUID
	Revision     int64
	SubmittedAt  pgtype.Timestamptz
	CorrectCount pgtype.Int4
	TotalCount   pgtype.Int4
}

func (q *Queries) SubmitAssessmentAttempt(ctx context.Context, arg SubmitAssessmentAttemptParams) (AssessmentsAssessmentAttempt, error) {
	row := q.db.QueryRow(ctx, submitAssessmentAttempt,
		arg.ID,
		arg.Revision,
		arg.SubmittedAt,
		arg.CorrectCount,
		arg.TotalCount,
	)
	var i AssessmentsAssessmentAttempt
	err := row.Scan(
		&i.ID,
		&i.LearnerUserID,
		&i.CourseVersionID,
		&i.AssessmentKey,
		&i.State,
		&i.Revision,
		&i.Responses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CorrectCount,
		&i.TotalCount,
	)
	return i, err
}

const updateAssessmentAttempt = `-- name: UpdateAssessmentAttempt :one
UPDATE assessments.assessment_attempt
SET responses = $3,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1 AND revision = $2 AND state = 'IN_PROGRESS'
RETURNING id, learner_user_id, course_version_id, assessment_key, state, revision, responses, created_at, updated_at, submitted_at, correct_count, total_count
`

type UpdateAssessmentAttemptParams struct {
	ID        pgtype.UUID
	Revision  int64
	Responses []byte
}

func (q *Queries) UpdateAssessmentAttempt(ctx context.Context, arg UpdateAssessmentAttemptParams) (AssessmentsAssessmentAttempt, error) {
	row := q.db.QueryRow(ctx, updateAssessmentAttempt, arg.ID, arg.Revision, arg.Responses)
	var i AssessmentsAssessmentAttempt
	err := row.Scan(
		&i.ID,
		&i.LearnerUserID,
		&i.CourseVersionID,
		&i.AssessmentKey,
		&i.State,
		&i.Revision,
		&i.Responses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.CorrectCount,
		&i.TotalCount,
	)
	return i, err
}
