// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssessmentsAssessment struct {
	ID              pgtype.UUID
	OwnerDraftID    pgtype.UUID
	Title           string
	Revision        int64
	Definition      []byte
	CreatedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
