// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAvailableAssetsForDraft = `-- name: CountAvailableAssetsForDraft :one
SELECT count(*)
FROM assets.asset
WHERE owner_draft_id = $1 AND lifecycle = 'AVAILABLE'
`

func (q *Queries) CountAvailableAssetsForDraft(ctx context.Context, ownerDraftID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableAssetsForDraft, ownerDraftID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets.asset (
    owner_draft_id, original_filename, media_type, byte_size, sha256_digest,
    storage_object_id, lifecycle, created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at, origin, import_id
`

type CreateAssetParams struct {
	OwnerDraftID     pgtype.UUID
	OriginalFilename string
	MediaType        string
	ByteSize         pgtype.Int8
	Sha256Digest     pgtype.Text
	StorageObjectID  pgtype.UUID
	Lifecycle        string
	CreatedByUserID  pgtype.UUID
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (AssetsAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.OwnerDraftID,
		arg.OriginalFilename,
		arg.MediaType,
		arg.ByteSize,
		arg.Sha256Digest,
		arg.StorageObjectID,
		arg.Lifecycle,
		arg.CreatedByUserID,
	)
	var i AssetsAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256Digest,
		&i.StorageObjectID,
		&i.Lifecycle,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Origin,
		&i.ImportID,
	)
	return i, err
}

const createImportedAvailableAsset = `-- name: CreateImportedAvailableAsset :one
INSERT INTO assets.asset (
    origin, import_id, original_filename, media_type, byte_size, sha256_digest,
    storage_object_id, lifecycle
)
VALUES ('PACKAGE_IMPORT', $1, $2, $3, $4, $5, $6, 'AVAILABLE')
RETURNING id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at, origin, import_id
`

type CreateImportedAvailableAssetParams struct {
	ImportID         pgtype.UUID
	OriginalFilename string
	MediaType        string
	ByteSize         pgtype.Int8
	Sha256Digest     pgtype.Text
	StorageObjectID  pgtype.UUID
}

func (q *Queries) CreateImportedAvailableAsset(ctx context.Context, arg CreateImportedAvailableAssetParams) (AssetsAsset, error) {
	row := q.db.QueryRow(ctx, createImportedAvailableAsset,
		arg.ImportID,
		arg.OriginalFilename,
		arg.MediaType,
		arg.ByteSize,
		arg.Sha256Digest,
		arg.StorageObjectID,
	)
	var i AssetsAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256Digest,
		&i.StorageObjectID,
		&i.Lifecycle,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Origin,
		&i.ImportID,
	)
	return i, err
}

const discardPendingAsset = `-- name: DiscardPendingAsset :execrows
DELETE FROM assets.asset
WHERE id = $1 AND lifecycle = 'PENDING'
`

func (q *Queries) DiscardPendingAsset(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, discardPendingAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAsset = `-- name: GetAsset :one
SELECT id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at, origin, import_id
FROM assets.asset
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (AssetsAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i AssetsAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256Digest,
		&i.StorageObjectID,
		&i.Lifecycle,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Origin,
		&i.ImportID,
	)
	return i, err
}

const listAvailableAssetsForDraft = `-- name: ListAvailableAssetsForDraft :many
SELECT id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at, origin, import_id
FROM assets.asset
WHERE owner_draft_id = $1 AND lifecycle = 'AVAILABLE'
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListAvailableAssetsForDraftParams struct {
	OwnerDraftID pgtype.UUID
	Offset       int32
	Limit        int32
}

func (q *Queries) ListAvailableAssetsForDraft(ctx context.Context, arg ListAvailableAssetsForDraftParams) ([]AssetsAsset, error) {
	rows, err := q.db.Query(ctx, listAvailableAssetsForDraft, arg.OwnerDraftID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetsAsset
	for rows.Next() {
		var i AssetsAsset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerDraftID,
			&i.OriginalFilename,
			&i.MediaType,
			&i.ByteSize,
			&i.Sha256Digest,
			&i.StorageObjectID,
			&i.Lifecycle,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.Origin,
			&i.ImportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssetAvailable = `-- name: MarkAssetAvailable :one
UPDATE assets.asset
SET lifecycle = 'AVAILABLE', byte_size = $2, sha256_digest = $3, storage_object_id = $4
WHERE id = $1 AND lifecycle = 'PENDING'
RETURNING id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at, origin, import_id
`

type MarkAssetAvailableParams struct {
	ID              pgtype.UUID
	ByteSize        pgtype.Int8
	Sha256Digest    pgtype.Text
	StorageObjectID pgtype.UUID
}

func (q *Queries) MarkAssetAvailable(ctx context.Context, arg MarkAssetAvailableParams) (AssetsAsset, error) {
	row := q.db.QueryRow(ctx, markAssetAvailable,
		arg.ID,
		arg.ByteSize,
		arg.Sha256Digest,
		arg.StorageObjectID,
	)
	var i AssetsAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256Digest,
		&i.StorageObjectID,
		&i.Lifecycle,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Origin,
		&i.ImportID,
	)
	return i, err
}
