// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets.asset (
    owner_draft_id, original_filename, media_type, byte_size, sha256_digest,
    storage_object_id, lifecycle, created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at
`

type CreateAssetParams struct {
	OwnerDraftID     pgtype.UUID
	OriginalFilename string
	MediaType        string
	ByteSize         pgtype.Int8
	Sha256Digest     pgtype.Text
	StorageObjectID  pgtype.UUID
	Lifecycle        string
	CreatedByUserID  pgtype.UUID
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (AssetsAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.OwnerDraftID,
		arg.OriginalFilename,
		arg.MediaType,
		arg.ByteSize,
		arg.Sha256Digest,
		arg.StorageObjectID,
		arg.Lifecycle,
		arg.CreatedByUserID,
	)
	var i AssetsAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256Digest,
		&i.StorageObjectID,
		&i.Lifecycle,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const discardPendingAsset = `-- name: DiscardPendingAsset :execrows
DELETE FROM assets.asset
WHERE id = $1 AND lifecycle = 'PENDING'
`

func (q *Queries) DiscardPendingAsset(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, discardPendingAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAsset = `-- name: GetAsset :one
SELECT id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at
FROM assets.asset
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (AssetsAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i AssetsAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256Digest,
		&i.StorageObjectID,
		&i.Lifecycle,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const markAssetAvailable = `-- name: MarkAssetAvailable :one
UPDATE assets.asset
SET lifecycle = 'AVAILABLE', byte_size = $2, sha256_digest = $3, storage_object_id = $4
WHERE id = $1 AND lifecycle = 'PENDING'
RETURNING id, owner_draft_id, original_filename, media_type, byte_size, sha256_digest, storage_object_id, lifecycle, created_by_user_id, created_at
`

type MarkAssetAvailableParams struct {
	ID              pgtype.UUID
	ByteSize        pgtype.Int8
	Sha256Digest    pgtype.Text
	StorageObjectID pgtype.UUID
}

func (q *Queries) MarkAssetAvailable(ctx context.Context, arg MarkAssetAvailableParams) (AssetsAsset, error) {
	row := q.db.QueryRow(ctx, markAssetAvailable,
		arg.ID,
		arg.ByteSize,
		arg.Sha256Digest,
		arg.StorageObjectID,
	)
	var i AssetsAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerDraftID,
		&i.OriginalFilename,
		&i.MediaType,
		&i.ByteSize,
		&i.Sha256Digest,
		&i.StorageObjectID,
		&i.Lifecycle,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
