// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetsAsset struct {
	ID               pgtype.UUID
	OwnerDraftID     pgtype.UUID
	OriginalFilename string
	MediaType        string
	ByteSize         pgtype.Int8
	Sha256Digest     pgtype.Text
	StorageObjectID  pgtype.UUID
	Lifecycle        string
	CreatedByUserID  pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}
