import { cleanup, fireEvent, render, screen } from '@testing-library/vue'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { AuthoringLessonContent, AuthoringLessonDetail } from '../authoring/authoring'
import AuthoringLessonContentEditor from './AuthoringLessonContentEditor.vue'

const replaceContent = vi.hoisted(() => vi.fn())
vi.mock('../authoring/authoring', async (original) => ({ ...(await original<typeof import('../authoring/authoring')>()), replaceAuthoringLessonContent: replaceContent, listAuthoringCourseWidgets: vi.fn().mockResolvedValue({ widgets: [] }) }))
const draftId='11111111-1111-4111-8111-111111111111', lessonId='22222222-2222-4222-8222-222222222222'
function lesson(content: AuthoringLessonContent={schemaVersion:1,blocks:[]}): AuthoringLessonDetail { return { id:lessonId,draft_id:draftId,module_id:'33333333-3333-4333-8333-333333333333',stable_key:'intro',title:'Introduction',description:'',objectives:[],estimated_duration_minutes:null,position:0,revision:7,recommended_prerequisite_keys:[],content,created_at:'',updated_at:'' } }
async function add(type:string) { await fireEvent.click(screen.getByRole('button',{name:'+ Add content'})); await fireEvent.click(screen.getByRole('button',{name:type})); if (type !== 'Divider') await fireEvent.click(screen.getByRole('button',{name:'Apply'})) }
async function edit(index:number) { await fireEvent.click(screen.getByRole('button',{name:new RegExp(`Edit block ${index}`)})) }
describe('AuthoringLessonContentEditor',()=>{
 beforeEach(()=>replaceContent.mockImplementation(async (...args: unknown[])=>{ const request=args[2] as { content: AuthoringLessonContent } | undefined; const content=request?.content ?? { schemaVersion: 1, blocks: [] }; return {lesson:{...lesson(content),revision:8,draftRevision:9},content} })); afterEach(cleanup)
 it('renders loaded blocks as compact rows and mounts one focused editor only when requested',async()=>{render(AuthoringLessonContentEditor,{props:{draftId,lesson:lesson({schemaVersion:1,blocks:[{key:'text',type:'TEXT',payload:{content:{nodes:[{type:'paragraph',content:[{type:'text',text:'Coupling describes the degree of dependency.'}]}]}}},{key:'divider',type:'DIVIDER',payload:{}}]})}}); expect(screen.getByText('Coupling describes the degree of dependency.')).toBeTruthy(); expect(screen.queryByRole('textbox')).toBeNull(); expect(screen.queryByRole('button',{name:/Edit block 2/})).toBeNull(); await edit(1); expect(screen.getByRole('dialog',{name:'Edit text block'})).toBeTruthy(); expect(screen.getByRole('textbox',{name:'Block 1 text · Paragraph 1 · Text 1'})).toBeTruthy() })
 it('applies a text edit locally, cancels isolated edits, and saves the complete document',async()=>{render(AuthoringLessonContentEditor,{props:{draftId,lesson:lesson()}}); await add('Text'); await edit(1); const text=screen.getByRole('textbox',{name:'Block 1 text · Paragraph 1 · Text 1'}); await fireEvent.update(text,'Applied text'); await fireEvent.click(screen.getByRole('button',{name:'Apply'})); expect(screen.getByText('Applied text')).toBeTruthy(); await edit(1); await fireEvent.update(screen.getByRole('textbox',{name:'Block 1 text · Paragraph 1 · Text 1'}),'Cancelled'); await fireEvent.click(screen.getByRole('button',{name:'Cancel'})); expect(screen.getByText('Applied text')).toBeTruthy(); expect(replaceContent).not.toHaveBeenCalled(); await fireEvent.click(screen.getByRole('button',{name:'Save Lesson content'})); expect(replaceContent.mock.calls[0][2].content.blocks[0].payload.content.nodes[0].content[0].text).toBe('Applied text') })
 it('keeps numbering and full replacement order after moving and removing blocks',async()=>{render(AuthoringLessonContentEditor,{props:{draftId,lesson:lesson()}}); await add('Text'); await add('Heading'); expect(screen.getAllByText(/0[12]/)).toHaveLength(2); await fireEvent.click(screen.getByRole('button',{name:'Actions for block 2, heading'})); await fireEvent.click(screen.getByRole('menuitem',{name:'Move up'})); await fireEvent.click(screen.getByRole('button',{name:'Actions for block 2, text'})); await fireEvent.click(screen.getByRole('menuitem',{name:'Remove'})); await fireEvent.click(screen.getByRole('button',{name:'Save Lesson content'})); expect((replaceContent.mock.calls[0]![2] as any).content.blocks.map((b:any)=>b.type)).toEqual(['HEADING']) })
 it('keeps picker and preview dirty warning available',async()=>{const {emitted}=render(AuthoringLessonContentEditor,{props:{draftId,lesson:lesson()}}); await fireEvent.click(screen.getByRole('button',{name:'Preview'})); expect(emitted().preview).toHaveLength(1); await add('Divider'); await fireEvent.click(screen.getByRole('button',{name:'Preview'})); expect(screen.getByRole('dialog',{name:'You have unsaved changes'})).toBeTruthy() })
 it('does not eagerly mount editors for a large lesson',()=>{const blocks=Array.from({length:25},(_,i)=>({key:`divider-${i}`,type:'DIVIDER' as const,payload:{}})); render(AuthoringLessonContentEditor,{props:{draftId,lesson:lesson({schemaVersion:1,blocks})}}); expect(screen.getAllByRole('separator')).toHaveLength(25); expect(screen.queryByRole('dialog',{name:/Edit/})).toBeNull() })
})
