// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PluginsDashboardWidgetPlacement struct {
	PlacementID    pgtype.UUID
	PluginID       string
	PluginVersion  string
	ArtifactDigest string
	WidgetID       string
	Configuration  []byte
	Position       int32
	Enabled        bool
	Revision       int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PluginsInstalledRelease struct {
	InstallationID  pgtype.UUID
	PluginID        string
	Version         string
	ArtifactDigest  string
	Manifest        []byte
	SignatureKeyID  pgtype.Text
	SignatureValue  pgtype.Text
	SigningPayload  []byte
	RegisteredTrust string
	State           string
	Enabled         bool
	InstalledAt     pgtype.Timestamptz
}

type PluginsInstalledResource struct {
	InstallationID pgtype.UUID
	ResourcePath   string
	Sha256Digest   string
	ByteSize       int64
	Content        []byte
}

type PluginsReleaseApproval struct {
	ApprovalID     pgtype.UUID
	PluginID       string
	Version        string
	ArtifactDigest string
	Kind           string
	AuthorityKeyID pgtype.Text
	ApprovedAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type PluginsVerificationKey struct {
	KeyID            string
	PublicKey        []byte
	Purpose          string
	AllowedPluginIds []string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
}
