// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDashboardWidgetPlacement = `-- name: CreateDashboardWidgetPlacement :one
INSERT INTO plugins.dashboard_widget_placement (placement_id, plugin_id, plugin_version, artifact_digest, widget_id, configuration, position, enabled, revision, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,(SELECT COALESCE(MAX(position)+1,0) FROM plugins.dashboard_widget_placement),$7,$8,$9,$10)
RETURNING placement_id, plugin_id, plugin_version, artifact_digest, widget_id, configuration, position, enabled, revision, created_at, updated_at
`

type CreateDashboardWidgetPlacementParams struct {
	PlacementID    pgtype.UUID
	PluginID       string
	PluginVersion  string
	ArtifactDigest string
	WidgetID       string
	Configuration  []byte
	Enabled        bool
	Revision       int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateDashboardWidgetPlacement(ctx context.Context, arg CreateDashboardWidgetPlacementParams) (PluginsDashboardWidgetPlacement, error) {
	row := q.db.QueryRow(ctx, createDashboardWidgetPlacement,
		arg.PlacementID,
		arg.PluginID,
		arg.PluginVersion,
		arg.ArtifactDigest,
		arg.WidgetID,
		arg.Configuration,
		arg.Enabled,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PluginsDashboardWidgetPlacement
	err := row.Scan(
		&i.PlacementID,
		&i.PluginID,
		&i.PluginVersion,
		&i.ArtifactDigest,
		&i.WidgetID,
		&i.Configuration,
		&i.Position,
		&i.Enabled,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReleaseApproval = `-- name: CreateReleaseApproval :exec
INSERT INTO plugins.release_approval (
  approval_id, plugin_id, version, artifact_digest, kind, authority_key_id, approved_at
) VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type CreateReleaseApprovalParams struct {
	ApprovalID     pgtype.UUID
	PluginID       string
	Version        string
	ArtifactDigest string
	Kind           string
	AuthorityKeyID pgtype.Text
	ApprovedAt     pgtype.Timestamptz
}

func (q *Queries) CreateReleaseApproval(ctx context.Context, arg CreateReleaseApprovalParams) error {
	_, err := q.db.Exec(ctx, createReleaseApproval,
		arg.ApprovalID,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.Kind,
		arg.AuthorityKeyID,
		arg.ApprovedAt,
	)
	return err
}

const deleteDashboardWidgetPlacement = `-- name: DeleteDashboardWidgetPlacement :execrows
DELETE FROM plugins.dashboard_widget_placement WHERE placement_id=$1 AND revision=$2
`

type DeleteDashboardWidgetPlacementParams struct {
	PlacementID pgtype.UUID
	Revision    int64
}

func (q *Queries) DeleteDashboardWidgetPlacement(ctx context.Context, arg DeleteDashboardWidgetPlacementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDashboardWidgetPlacement, arg.PlacementID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveReleaseApproval = `-- name: FindActiveReleaseApproval :one
SELECT approval_id, plugin_id, version, artifact_digest, kind, authority_key_id, approved_at, revoked_at FROM plugins.release_approval
WHERE plugin_id = $1 AND version = $2 AND artifact_digest = $3 AND kind = $4
  AND COALESCE(authority_key_id, '') = $5 AND revoked_at IS NULL
`

type FindActiveReleaseApprovalParams struct {
	PluginID       string
	Version        string
	ArtifactDigest string
	Kind           string
	AuthorityKeyID pgtype.Text
}

func (q *Queries) FindActiveReleaseApproval(ctx context.Context, arg FindActiveReleaseApprovalParams) (PluginsReleaseApproval, error) {
	row := q.db.QueryRow(ctx, findActiveReleaseApproval,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.Kind,
		arg.AuthorityKeyID,
	)
	var i PluginsReleaseApproval
	err := row.Scan(
		&i.ApprovalID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Kind,
		&i.AuthorityKeyID,
		&i.ApprovedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDashboardWidgetPlacement = `-- name: GetDashboardWidgetPlacement :one
SELECT placement_id, plugin_id, plugin_version, artifact_digest, widget_id, configuration, position, enabled, revision, created_at, updated_at FROM plugins.dashboard_widget_placement WHERE placement_id = $1
`

func (q *Queries) GetDashboardWidgetPlacement(ctx context.Context, placementID pgtype.UUID) (PluginsDashboardWidgetPlacement, error) {
	row := q.db.QueryRow(ctx, getDashboardWidgetPlacement, placementID)
	var i PluginsDashboardWidgetPlacement
	err := row.Scan(
		&i.PlacementID,
		&i.PluginID,
		&i.PluginVersion,
		&i.ArtifactDigest,
		&i.WidgetID,
		&i.Configuration,
		&i.Position,
		&i.Enabled,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstalledRelease = `-- name: GetInstalledRelease :one
SELECT installation_id, plugin_id, version, artifact_digest, manifest, signature_key_id, signature_value, signing_payload, registered_trust, state, enabled, installed_at FROM plugins.installed_release WHERE plugin_id = $1 AND version = $2
`

type GetInstalledReleaseParams struct {
	PluginID string
	Version  string
}

func (q *Queries) GetInstalledRelease(ctx context.Context, arg GetInstalledReleaseParams) (PluginsInstalledRelease, error) {
	row := q.db.QueryRow(ctx, getInstalledRelease, arg.PluginID, arg.Version)
	var i PluginsInstalledRelease
	err := row.Scan(
		&i.InstallationID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Manifest,
		&i.SignatureKeyID,
		&i.SignatureValue,
		&i.SigningPayload,
		&i.RegisteredTrust,
		&i.State,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const getInstalledResource = `-- name: GetInstalledResource :one
SELECT r.installation_id, r.resource_path, r.sha256_digest, r.byte_size, r.content
FROM plugins.installed_resource r
JOIN plugins.installed_release p ON p.installation_id = r.installation_id
WHERE p.plugin_id = $1 AND p.version = $2 AND p.artifact_digest = $3
  AND r.resource_path = $4
`

type GetInstalledResourceParams struct {
	PluginID       string
	Version        string
	ArtifactDigest string
	ResourcePath   string
}

func (q *Queries) GetInstalledResource(ctx context.Context, arg GetInstalledResourceParams) (PluginsInstalledResource, error) {
	row := q.db.QueryRow(ctx, getInstalledResource,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.ResourcePath,
	)
	var i PluginsInstalledResource
	err := row.Scan(
		&i.InstallationID,
		&i.ResourcePath,
		&i.Sha256Digest,
		&i.ByteSize,
		&i.Content,
	)
	return i, err
}

const getVerificationKey = `-- name: GetVerificationKey :one
SELECT key_id, public_key, purpose, allowed_plugin_ids, enabled, created_at FROM plugins.verification_key WHERE key_id = $1
`

func (q *Queries) GetVerificationKey(ctx context.Context, keyID string) (PluginsVerificationKey, error) {
	row := q.db.QueryRow(ctx, getVerificationKey, keyID)
	var i PluginsVerificationKey
	err := row.Scan(
		&i.KeyID,
		&i.PublicKey,
		&i.Purpose,
		&i.AllowedPluginIds,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listDashboardWidgetPlacements = `-- name: ListDashboardWidgetPlacements :many
SELECT placement_id, plugin_id, plugin_version, artifact_digest, widget_id, configuration, position, enabled, revision, created_at, updated_at FROM plugins.dashboard_widget_placement ORDER BY position, placement_id
`

func (q *Queries) ListDashboardWidgetPlacements(ctx context.Context) ([]PluginsDashboardWidgetPlacement, error) {
	rows, err := q.db.Query(ctx, listDashboardWidgetPlacements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginsDashboardWidgetPlacement
	for rows.Next() {
		var i PluginsDashboardWidgetPlacement
		if err := rows.Scan(
			&i.PlacementID,
			&i.PluginID,
			&i.PluginVersion,
			&i.ArtifactDigest,
			&i.WidgetID,
			&i.Configuration,
			&i.Position,
			&i.Enabled,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstalledReleases = `-- name: ListInstalledReleases :many
SELECT installation_id, plugin_id, version, artifact_digest, manifest, signature_key_id, signature_value, signing_payload, registered_trust, state, enabled, installed_at FROM plugins.installed_release ORDER BY plugin_id, version
`

func (q *Queries) ListInstalledReleases(ctx context.Context) ([]PluginsInstalledRelease, error) {
	rows, err := q.db.Query(ctx, listInstalledReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginsInstalledRelease
	for rows.Next() {
		var i PluginsInstalledRelease
		if err := rows.Scan(
			&i.InstallationID,
			&i.PluginID,
			&i.Version,
			&i.ArtifactDigest,
			&i.Manifest,
			&i.SignatureKeyID,
			&i.SignatureValue,
			&i.SigningPayload,
			&i.RegisteredTrust,
			&i.State,
			&i.Enabled,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerInstalledRelease = `-- name: RegisterInstalledRelease :one
INSERT INTO plugins.installed_release (
  installation_id, plugin_id, version, artifact_digest, manifest,
  signature_key_id, signature_value, signing_payload, registered_trust, installed_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (plugin_id, version) DO NOTHING
RETURNING installation_id, plugin_id, version, artifact_digest, manifest, signature_key_id, signature_value, signing_payload, registered_trust, state, enabled, installed_at
`

type RegisterInstalledReleaseParams struct {
	InstallationID  pgtype.UUID
	PluginID        string
	Version         string
	ArtifactDigest  string
	Manifest        []byte
	SignatureKeyID  pgtype.Text
	SignatureValue  pgtype.Text
	SigningPayload  []byte
	RegisteredTrust string
	InstalledAt     pgtype.Timestamptz
}

func (q *Queries) RegisterInstalledRelease(ctx context.Context, arg RegisterInstalledReleaseParams) (PluginsInstalledRelease, error) {
	row := q.db.QueryRow(ctx, registerInstalledRelease,
		arg.InstallationID,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.Manifest,
		arg.SignatureKeyID,
		arg.SignatureValue,
		arg.SigningPayload,
		arg.RegisteredTrust,
		arg.InstalledAt,
	)
	var i PluginsInstalledRelease
	err := row.Scan(
		&i.InstallationID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Manifest,
		&i.SignatureKeyID,
		&i.SignatureValue,
		&i.SigningPayload,
		&i.RegisteredTrust,
		&i.State,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const registerInstalledResource = `-- name: RegisterInstalledResource :exec
INSERT INTO plugins.installed_resource (
  installation_id, resource_path, sha256_digest, byte_size, content
) VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (installation_id, resource_path) DO NOTHING
`

type RegisterInstalledResourceParams struct {
	InstallationID pgtype.UUID
	ResourcePath   string
	Sha256Digest   string
	ByteSize       int64
	Content        []byte
}

func (q *Queries) RegisterInstalledResource(ctx context.Context, arg RegisterInstalledResourceParams) error {
	_, err := q.db.Exec(ctx, registerInstalledResource,
		arg.InstallationID,
		arg.ResourcePath,
		arg.Sha256Digest,
		arg.ByteSize,
		arg.Content,
	)
	return err
}

const registerVerificationKey = `-- name: RegisterVerificationKey :one
INSERT INTO plugins.verification_key (key_id, public_key, purpose, allowed_plugin_ids, enabled)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key_id) DO NOTHING
RETURNING key_id, public_key, purpose, allowed_plugin_ids, enabled, created_at
`

type RegisterVerificationKeyParams struct {
	KeyID            string
	PublicKey        []byte
	Purpose          string
	AllowedPluginIds []string
	Enabled          bool
}

func (q *Queries) RegisterVerificationKey(ctx context.Context, arg RegisterVerificationKeyParams) (PluginsVerificationKey, error) {
	row := q.db.QueryRow(ctx, registerVerificationKey,
		arg.KeyID,
		arg.PublicKey,
		arg.Purpose,
		arg.AllowedPluginIds,
		arg.Enabled,
	)
	var i PluginsVerificationKey
	err := row.Scan(
		&i.KeyID,
		&i.PublicKey,
		&i.Purpose,
		&i.AllowedPluginIds,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const revokeReleaseApproval = `-- name: RevokeReleaseApproval :execrows
UPDATE plugins.release_approval SET revoked_at = $2
WHERE approval_id = $1 AND revoked_at IS NULL
`

type RevokeReleaseApprovalParams struct {
	ApprovalID pgtype.UUID
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) RevokeReleaseApproval(ctx context.Context, arg RevokeReleaseApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeReleaseApproval, arg.ApprovalID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstalledReleaseEnabled = `-- name: SetInstalledReleaseEnabled :one
UPDATE plugins.installed_release
SET enabled = $2, state = CASE WHEN $2 THEN 'INSTALLED' ELSE 'DISABLED' END
WHERE installation_id = $1
RETURNING installation_id, plugin_id, version, artifact_digest, manifest, signature_key_id, signature_value, signing_payload, registered_trust, state, enabled, installed_at
`

type SetInstalledReleaseEnabledParams struct {
	InstallationID pgtype.UUID
	Enabled        bool
}

func (q *Queries) SetInstalledReleaseEnabled(ctx context.Context, arg SetInstalledReleaseEnabledParams) (PluginsInstalledRelease, error) {
	row := q.db.QueryRow(ctx, setInstalledReleaseEnabled, arg.InstallationID, arg.Enabled)
	var i PluginsInstalledRelease
	err := row.Scan(
		&i.InstallationID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Manifest,
		&i.SignatureKeyID,
		&i.SignatureValue,
		&i.SigningPayload,
		&i.RegisteredTrust,
		&i.State,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const setVerificationKeyEnabled = `-- name: SetVerificationKeyEnabled :execrows
UPDATE plugins.verification_key SET enabled = $2 WHERE key_id = $1
`

type SetVerificationKeyEnabledParams struct {
	KeyID   string
	Enabled bool
}

func (q *Queries) SetVerificationKeyEnabled(ctx context.Context, arg SetVerificationKeyEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVerificationKeyEnabled, arg.KeyID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDashboardWidgetPlacement = `-- name: UpdateDashboardWidgetPlacement :one
UPDATE plugins.dashboard_widget_placement SET configuration=$2, enabled=$3, revision=revision+1, updated_at=$4
WHERE placement_id=$1 AND revision=$5 RETURNING placement_id, plugin_id, plugin_version, artifact_digest, widget_id, configuration, position, enabled, revision, created_at, updated_at
`

type UpdateDashboardWidgetPlacementParams struct {
	PlacementID   pgtype.UUID
	Configuration []byte
	Enabled       bool
	UpdatedAt     pgtype.Timestamptz
	Revision      int64
}

func (q *Queries) UpdateDashboardWidgetPlacement(ctx context.Context, arg UpdateDashboardWidgetPlacementParams) (PluginsDashboardWidgetPlacement, error) {
	row := q.db.QueryRow(ctx, updateDashboardWidgetPlacement,
		arg.PlacementID,
		arg.Configuration,
		arg.Enabled,
		arg.UpdatedAt,
		arg.Revision,
	)
	var i PluginsDashboardWidgetPlacement
	err := row.Scan(
		&i.PlacementID,
		&i.PluginID,
		&i.PluginVersion,
		&i.ArtifactDigest,
		&i.WidgetID,
		&i.Configuration,
		&i.Position,
		&i.Enabled,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
