// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReleaseApproval = `-- name: CreateReleaseApproval :exec
INSERT INTO plugins.release_approval (
  approval_id, plugin_id, version, artifact_digest, kind, authority_key_id, approved_at
) VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type CreateReleaseApprovalParams struct {
	ApprovalID     pgtype.UUID
	PluginID       string
	Version        string
	ArtifactDigest string
	Kind           string
	AuthorityKeyID pgtype.Text
	ApprovedAt     pgtype.Timestamptz
}

func (q *Queries) CreateReleaseApproval(ctx context.Context, arg CreateReleaseApprovalParams) error {
	_, err := q.db.Exec(ctx, createReleaseApproval,
		arg.ApprovalID,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.Kind,
		arg.AuthorityKeyID,
		arg.ApprovedAt,
	)
	return err
}

const findActiveReleaseApproval = `-- name: FindActiveReleaseApproval :one
SELECT approval_id, plugin_id, version, artifact_digest, kind, authority_key_id, approved_at, revoked_at FROM plugins.release_approval
WHERE plugin_id = $1 AND version = $2 AND artifact_digest = $3 AND kind = $4
  AND COALESCE(authority_key_id, '') = $5 AND revoked_at IS NULL
`

type FindActiveReleaseApprovalParams struct {
	PluginID       string
	Version        string
	ArtifactDigest string
	Kind           string
	AuthorityKeyID pgtype.Text
}

func (q *Queries) FindActiveReleaseApproval(ctx context.Context, arg FindActiveReleaseApprovalParams) (PluginsReleaseApproval, error) {
	row := q.db.QueryRow(ctx, findActiveReleaseApproval,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.Kind,
		arg.AuthorityKeyID,
	)
	var i PluginsReleaseApproval
	err := row.Scan(
		&i.ApprovalID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Kind,
		&i.AuthorityKeyID,
		&i.ApprovedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getInstalledRelease = `-- name: GetInstalledRelease :one
SELECT installation_id, plugin_id, version, artifact_digest, manifest, signature_key_id, signature_value, signing_payload, registered_trust, state, enabled, installed_at FROM plugins.installed_release WHERE plugin_id = $1 AND version = $2
`

type GetInstalledReleaseParams struct {
	PluginID string
	Version  string
}

func (q *Queries) GetInstalledRelease(ctx context.Context, arg GetInstalledReleaseParams) (PluginsInstalledRelease, error) {
	row := q.db.QueryRow(ctx, getInstalledRelease, arg.PluginID, arg.Version)
	var i PluginsInstalledRelease
	err := row.Scan(
		&i.InstallationID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Manifest,
		&i.SignatureKeyID,
		&i.SignatureValue,
		&i.SigningPayload,
		&i.RegisteredTrust,
		&i.State,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const getInstalledResource = `-- name: GetInstalledResource :one
SELECT r.installation_id, r.resource_path, r.sha256_digest, r.byte_size, r.content
FROM plugins.installed_resource r
JOIN plugins.installed_release p ON p.installation_id = r.installation_id
WHERE p.plugin_id = $1 AND p.version = $2 AND p.artifact_digest = $3
  AND r.resource_path = $4
`

type GetInstalledResourceParams struct {
	PluginID       string
	Version        string
	ArtifactDigest string
	ResourcePath   string
}

func (q *Queries) GetInstalledResource(ctx context.Context, arg GetInstalledResourceParams) (PluginsInstalledResource, error) {
	row := q.db.QueryRow(ctx, getInstalledResource,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.ResourcePath,
	)
	var i PluginsInstalledResource
	err := row.Scan(
		&i.InstallationID,
		&i.ResourcePath,
		&i.Sha256Digest,
		&i.ByteSize,
		&i.Content,
	)
	return i, err
}

const getVerificationKey = `-- name: GetVerificationKey :one
SELECT key_id, public_key, purpose, allowed_plugin_ids, enabled, created_at FROM plugins.verification_key WHERE key_id = $1
`

func (q *Queries) GetVerificationKey(ctx context.Context, keyID string) (PluginsVerificationKey, error) {
	row := q.db.QueryRow(ctx, getVerificationKey, keyID)
	var i PluginsVerificationKey
	err := row.Scan(
		&i.KeyID,
		&i.PublicKey,
		&i.Purpose,
		&i.AllowedPluginIds,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const registerInstalledRelease = `-- name: RegisterInstalledRelease :one
INSERT INTO plugins.installed_release (
  installation_id, plugin_id, version, artifact_digest, manifest,
  signature_key_id, signature_value, signing_payload, registered_trust, installed_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (plugin_id, version) DO NOTHING
RETURNING installation_id, plugin_id, version, artifact_digest, manifest, signature_key_id, signature_value, signing_payload, registered_trust, state, enabled, installed_at
`

type RegisterInstalledReleaseParams struct {
	InstallationID  pgtype.UUID
	PluginID        string
	Version         string
	ArtifactDigest  string
	Manifest        []byte
	SignatureKeyID  pgtype.Text
	SignatureValue  pgtype.Text
	SigningPayload  []byte
	RegisteredTrust string
	InstalledAt     pgtype.Timestamptz
}

func (q *Queries) RegisterInstalledRelease(ctx context.Context, arg RegisterInstalledReleaseParams) (PluginsInstalledRelease, error) {
	row := q.db.QueryRow(ctx, registerInstalledRelease,
		arg.InstallationID,
		arg.PluginID,
		arg.Version,
		arg.ArtifactDigest,
		arg.Manifest,
		arg.SignatureKeyID,
		arg.SignatureValue,
		arg.SigningPayload,
		arg.RegisteredTrust,
		arg.InstalledAt,
	)
	var i PluginsInstalledRelease
	err := row.Scan(
		&i.InstallationID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Manifest,
		&i.SignatureKeyID,
		&i.SignatureValue,
		&i.SigningPayload,
		&i.RegisteredTrust,
		&i.State,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const registerInstalledResource = `-- name: RegisterInstalledResource :exec
INSERT INTO plugins.installed_resource (
  installation_id, resource_path, sha256_digest, byte_size, content
) VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (installation_id, resource_path) DO NOTHING
`

type RegisterInstalledResourceParams struct {
	InstallationID pgtype.UUID
	ResourcePath   string
	Sha256Digest   string
	ByteSize       int64
	Content        []byte
}

func (q *Queries) RegisterInstalledResource(ctx context.Context, arg RegisterInstalledResourceParams) error {
	_, err := q.db.Exec(ctx, registerInstalledResource,
		arg.InstallationID,
		arg.ResourcePath,
		arg.Sha256Digest,
		arg.ByteSize,
		arg.Content,
	)
	return err
}

const registerVerificationKey = `-- name: RegisterVerificationKey :one
INSERT INTO plugins.verification_key (key_id, public_key, purpose, allowed_plugin_ids, enabled)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key_id) DO NOTHING
RETURNING key_id, public_key, purpose, allowed_plugin_ids, enabled, created_at
`

type RegisterVerificationKeyParams struct {
	KeyID            string
	PublicKey        []byte
	Purpose          string
	AllowedPluginIds []string
	Enabled          bool
}

func (q *Queries) RegisterVerificationKey(ctx context.Context, arg RegisterVerificationKeyParams) (PluginsVerificationKey, error) {
	row := q.db.QueryRow(ctx, registerVerificationKey,
		arg.KeyID,
		arg.PublicKey,
		arg.Purpose,
		arg.AllowedPluginIds,
		arg.Enabled,
	)
	var i PluginsVerificationKey
	err := row.Scan(
		&i.KeyID,
		&i.PublicKey,
		&i.Purpose,
		&i.AllowedPluginIds,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const revokeReleaseApproval = `-- name: RevokeReleaseApproval :execrows
UPDATE plugins.release_approval SET revoked_at = $2
WHERE approval_id = $1 AND revoked_at IS NULL
`

type RevokeReleaseApprovalParams struct {
	ApprovalID pgtype.UUID
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) RevokeReleaseApproval(ctx context.Context, arg RevokeReleaseApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeReleaseApproval, arg.ApprovalID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstalledReleaseEnabled = `-- name: SetInstalledReleaseEnabled :one
UPDATE plugins.installed_release
SET enabled = $2, state = CASE WHEN $2 THEN 'INSTALLED' ELSE 'DISABLED' END
WHERE installation_id = $1
RETURNING installation_id, plugin_id, version, artifact_digest, manifest, signature_key_id, signature_value, signing_payload, registered_trust, state, enabled, installed_at
`

type SetInstalledReleaseEnabledParams struct {
	InstallationID pgtype.UUID
	Enabled        bool
}

func (q *Queries) SetInstalledReleaseEnabled(ctx context.Context, arg SetInstalledReleaseEnabledParams) (PluginsInstalledRelease, error) {
	row := q.db.QueryRow(ctx, setInstalledReleaseEnabled, arg.InstallationID, arg.Enabled)
	var i PluginsInstalledRelease
	err := row.Scan(
		&i.InstallationID,
		&i.PluginID,
		&i.Version,
		&i.ArtifactDigest,
		&i.Manifest,
		&i.SignatureKeyID,
		&i.SignatureValue,
		&i.SigningPayload,
		&i.RegisteredTrust,
		&i.State,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const setVerificationKeyEnabled = `-- name: SetVerificationKeyEnabled :execrows
UPDATE plugins.verification_key SET enabled = $2 WHERE key_id = $1
`

type SetVerificationKeyEnabledParams struct {
	KeyID   string
	Enabled bool
}

func (q *Queries) SetVerificationKeyEnabled(ctx context.Context, arg SetVerificationKeyEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVerificationKeyEnabled, arg.KeyID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
