// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           pgtype.UUID
	Action       string
	ActorKind    string
	ResourceType string
	ResourceID   pgtype.UUID
	Outcome      string
	OperationID  pgtype.UUID
	OccurredAt   pgtype.Timestamptz
}
