// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignGlobalRole = `-- name: AssignGlobalRole :one
INSERT INTO identity.global_role_assignments (user_id, role, granted_by)
VALUES ($1, $2, $3) RETURNING id, user_id, role, granted_at, granted_by, revoked_at
`

type AssignGlobalRoleParams struct {
	UserID    pgtype.UUID
	Role      string
	GrantedBy pgtype.UUID
}

func (q *Queries) AssignGlobalRole(ctx context.Context, arg AssignGlobalRoleParams) (IdentityGlobalRoleAssignment, error) {
	row := q.db.QueryRow(ctx, assignGlobalRole, arg.UserID, arg.Role, arg.GrantedBy)
	var i IdentityGlobalRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.GrantedAt,
		&i.GrantedBy,
		&i.RevokedAt,
	)
	return i, err
}

const createLocalPasswordCredential = `-- name: CreateLocalPasswordCredential :one
INSERT INTO identity.local_password_credentials (user_id, password_hash)
VALUES ($1, $2) RETURNING user_id, password_hash, created_at, updated_at
`

type CreateLocalPasswordCredentialParams struct {
	UserID       pgtype.UUID
	PasswordHash string
}

func (q *Queries) CreateLocalPasswordCredential(ctx context.Context, arg CreateLocalPasswordCredentialParams) (IdentityLocalPasswordCredential, error) {
	row := q.db.QueryRow(ctx, createLocalPasswordCredential, arg.UserID, arg.PasswordHash)
	var i IdentityLocalPasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO identity.sessions (user_id, token_digest, expires_at, csrf_token)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, token_digest, created_at, last_seen_at, expires_at, revoked_at, csrf_token
`

type CreateSessionParams struct {
	UserID      pgtype.UUID
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
	CsrfToken   pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.CsrfToken,
	)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CsrfToken,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (status) VALUES ($1) RETURNING id, status, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, status string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, createUser, status)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserEmail = `-- name: CreateUserEmail :one
INSERT INTO identity.user_emails (user_id, normalized_email, display_email, is_primary)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, normalized_email, display_email, verified_at, is_primary, created_at
`

type CreateUserEmailParams struct {
	UserID          pgtype.UUID
	NormalizedEmail string
	DisplayEmail    string
	IsPrimary       bool
}

func (q *Queries) CreateUserEmail(ctx context.Context, arg CreateUserEmailParams) (IdentityUserEmail, error) {
	row := q.db.QueryRow(ctx, createUserEmail,
		arg.UserID,
		arg.NormalizedEmail,
		arg.DisplayEmail,
		arg.IsPrimary,
	)
	var i IdentityUserEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NormalizedEmail,
		&i.DisplayEmail,
		&i.VerifiedAt,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalPasswordCredential = `-- name: GetLocalPasswordCredential :one
SELECT user_id, password_hash, created_at, updated_at FROM identity.local_password_credentials WHERE user_id = $1
`

func (q *Queries) GetLocalPasswordCredential(ctx context.Context, userID pgtype.UUID) (IdentityLocalPasswordCredential, error) {
	row := q.db.QueryRow(ctx, getLocalPasswordCredential, userID)
	var i IdentityLocalPasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrimaryUserEmail = `-- name: GetPrimaryUserEmail :one
SELECT id, user_id, normalized_email, display_email, verified_at, is_primary, created_at FROM identity.user_emails WHERE user_id = $1 AND is_primary
`

func (q *Queries) GetPrimaryUserEmail(ctx context.Context, userID pgtype.UUID) (IdentityUserEmail, error) {
	row := q.db.QueryRow(ctx, getPrimaryUserEmail, userID)
	var i IdentityUserEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NormalizedEmail,
		&i.DisplayEmail,
		&i.VerifiedAt,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByDigest = `-- name: GetSessionByDigest :one
SELECT id, user_id, token_digest, created_at, last_seen_at, expires_at, revoked_at, csrf_token FROM identity.sessions WHERE token_digest = $1
`

func (q *Queries) GetSessionByDigest(ctx context.Context, tokenDigest []byte) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, getSessionByDigest, tokenDigest)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CsrfToken,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_digest, created_at, last_seen_at, expires_at, revoked_at, csrf_token FROM identity.sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CsrfToken,
	)
	return i, err
}

const getSessionCSRFToken = `-- name: GetSessionCSRFToken :one
SELECT s.csrf_token FROM identity.sessions s
JOIN identity.users u ON u.id = s.user_id
WHERE s.id = $1 AND s.revoked_at IS NULL AND s.expires_at > now() AND u.status = 'ACTIVE'
`

func (q *Queries) GetSessionCSRFToken(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getSessionCSRFToken, id)
	var csrf_token pgtype.Text
	err := row.Scan(&csrf_token)
	return csrf_token, err
}

const getUser = `-- name: GetUser :one
SELECT id, status, created_at, updated_at FROM identity.users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserEmailByNormalized = `-- name: GetUserEmailByNormalized :one
SELECT id, user_id, normalized_email, display_email, verified_at, is_primary, created_at FROM identity.user_emails WHERE normalized_email = $1
`

func (q *Queries) GetUserEmailByNormalized(ctx context.Context, normalizedEmail string) (IdentityUserEmail, error) {
	row := q.db.QueryRow(ctx, getUserEmailByNormalized, normalizedEmail)
	var i IdentityUserEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NormalizedEmail,
		&i.DisplayEmail,
		&i.VerifiedAt,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveGlobalRole = `-- name: HasActiveGlobalRole :one
SELECT EXISTS(SELECT 1 FROM identity.global_role_assignments WHERE user_id = $1 AND role = $2 AND revoked_at IS NULL)
`

type HasActiveGlobalRoleParams struct {
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) HasActiveGlobalRole(ctx context.Context, arg HasActiveGlobalRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveGlobalRole, arg.UserID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const initializeSessionCSRFToken = `-- name: InitializeSessionCSRFToken :one
UPDATE identity.sessions s SET csrf_token = $2
FROM identity.users u
WHERE s.id = $1 AND s.user_id = u.id AND s.csrf_token IS NULL
  AND s.revoked_at IS NULL AND s.expires_at > now() AND u.status = 'ACTIVE'
RETURNING s.csrf_token
`

type InitializeSessionCSRFTokenParams struct {
	ID        pgtype.UUID
	CsrfToken pgtype.Text
}

func (q *Queries) InitializeSessionCSRFToken(ctx context.Context, arg InitializeSessionCSRFTokenParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, initializeSessionCSRFToken, arg.ID, arg.CsrfToken)
	var csrf_token pgtype.Text
	err := row.Scan(&csrf_token)
	return csrf_token, err
}

const listActiveGlobalRoles = `-- name: ListActiveGlobalRoles :many
SELECT id, user_id, role, granted_at, granted_by, revoked_at FROM identity.global_role_assignments WHERE user_id = $1 AND revoked_at IS NULL ORDER BY granted_at DESC
`

func (q *Queries) ListActiveGlobalRoles(ctx context.Context, userID pgtype.UUID) ([]IdentityGlobalRoleAssignment, error) {
	rows, err := q.db.Query(ctx, listActiveGlobalRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityGlobalRoleAssignment
	for rows.Next() {
		var i IdentityGlobalRoleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.GrantedAt,
			&i.GrantedBy,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE identity.user_emails SET verified_at = $2 WHERE id = $1 AND verified_at IS NULL RETURNING id, user_id, normalized_email, display_email, verified_at, is_primary, created_at
`

type MarkUserEmailVerifiedParams struct {
	ID         pgtype.UUID
	VerifiedAt pgtype.Timestamptz
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) (IdentityUserEmail, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, arg.ID, arg.VerifiedAt)
	var i IdentityUserEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NormalizedEmail,
		&i.DisplayEmail,
		&i.VerifiedAt,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const replaceLocalPasswordHash = `-- name: ReplaceLocalPasswordHash :one
UPDATE identity.local_password_credentials SET password_hash = $2, updated_at = now()
WHERE user_id = $1 RETURNING user_id, password_hash, created_at, updated_at
`

type ReplaceLocalPasswordHashParams struct {
	UserID       pgtype.UUID
	PasswordHash string
}

func (q *Queries) ReplaceLocalPasswordHash(ctx context.Context, arg ReplaceLocalPasswordHashParams) (IdentityLocalPasswordCredential, error) {
	row := q.db.QueryRow(ctx, replaceLocalPasswordHash, arg.UserID, arg.PasswordHash)
	var i IdentityLocalPasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeGlobalRole = `-- name: RevokeGlobalRole :one
UPDATE identity.global_role_assignments SET revoked_at = now()
WHERE user_id = $1 AND role = $2 AND revoked_at IS NULL RETURNING id, user_id, role, granted_at, granted_by, revoked_at
`

type RevokeGlobalRoleParams struct {
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) RevokeGlobalRole(ctx context.Context, arg RevokeGlobalRoleParams) (IdentityGlobalRoleAssignment, error) {
	row := q.db.QueryRow(ctx, revokeGlobalRole, arg.UserID, arg.Role)
	var i IdentityGlobalRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.GrantedAt,
		&i.GrantedBy,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE identity.sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL RETURNING id, user_id, token_digest, created_at, last_seen_at, expires_at, revoked_at, csrf_token
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, revokeSession, id)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CsrfToken,
	)
	return i, err
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE identity.sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :one
UPDATE identity.sessions SET last_seen_at = now() WHERE id = $1 AND revoked_at IS NULL RETURNING id, user_id, token_digest, created_at, last_seen_at, expires_at, revoked_at, csrf_token
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, updateSessionLastSeen, id)
	var i IdentitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CsrfToken,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE identity.users SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, status, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
