// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityGlobalRoleAssignment struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	GrantedAt pgtype.Timestamptz
	GrantedBy pgtype.UUID
	RevokedAt pgtype.Timestamptz
}

type IdentityLocalPasswordCredential struct {
	UserID pgtype.UUID
	// Sensitive password verifier; never log or expose through unrelated queries
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type IdentitySession struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	// SHA-256 digest of opaque session token; raw browser token must not be stored
	TokenDigest []byte
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type IdentityUser struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IdentityUserEmail struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	NormalizedEmail string
	DisplayEmail    string
	VerifiedAt      pgtype.Timestamptz
	IsPrimary       bool
	CreatedAt       pgtype.Timestamptz
}
