/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/authoring/drafts/{draftId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthoringDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Updates only mutable draft metadata using an explicit optimistic-concurrency revision. The request requires the authenticated session's CSRF token and a trusted same-origin Origin. Responses are private and not cacheable. */
        patch: operations["updateAuthoringDraftMetadata"];
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthoringWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates one draft Module at a zero-based position using the current draft revision. The authenticated session must provide a valid CSRF token and trusted same-origin Origin. */
        post: operations["createAuthoringModule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Adds an active AUTHOR or MAINTAINER membership using the Draft revision. The authenticated actor must have authoring.members.manage. */
        post: operations["addAuthoringMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Revokes one active membership while preserving history. Revoking the final active MAINTAINER is rejected. */
        delete: operations["revokeAuthoringMember"];
        options?: never;
        head?: never;
        /** @description Replaces one active member role. Demoting the final active MAINTAINER is rejected. */
        patch: operations["changeAuthoringMemberRole"];
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/modules/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Atomically replaces the complete ordered Module ID list for one Draft. The list must contain every current Module exactly once. */
        put: operations["reorderAuthoringModules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/modules/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Deletes an empty Module only. Modules containing Lessons are rejected so the lesson cascade remains unavailable through this API. */
        delete: operations["deleteAuthoringModule"];
        options?: never;
        head?: never;
        /** @description Updates title and description only. Stable key and position are immutable through PATCH. */
        patch: operations["updateAuthoringModule"];
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/modules/{moduleId}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuthoringLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/lessons/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Atomically replaces the complete ordered Lesson structure for every Module in the Draft; this permits moves without changing Lesson identity or stable key. */
        put: operations["reorderAuthoringLessons"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthoringLesson"];
        put?: never;
        post?: never;
        /** @description Deletes one draft Lesson and explicitly removes incoming advisory prerequisite relations, advancing affected source Lesson revisions. */
        delete: operations["deleteAuthoringLesson"];
        options?: never;
        head?: never;
        /** @description Updates Lesson metadata only. Stable key, Module, position, prerequisites, and content have separate boundaries. */
        patch: operations["updateAuthoringLesson"];
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/lessons/{lessonId}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Replaces the complete ordered advisory prerequisite stable-key list for one Lesson. Cycles are not evaluated in this slice. */
        put: operations["replaceAuthoringLessonPrerequisites"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/lessons/{lessonId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Atomically replaces the complete canonical semantic LessonContent document for one draft Lesson using its current revision. Editor state and partial block updates are not accepted. */
        put: operations["replaceAuthoringLessonContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authoring/drafts/{draftId}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthoringDraftStructure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublishedCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{slug}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCourseVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{slug}/versions/{version}/lessons/{lessonKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Authenticate a local password and set the opaque HttpOnly session cookie. A trusted same-origin Origin header is required; the response includes a separate session-bound CSRF token. Source rate limiting and bounded concurrent authentication work may reject requests before password verification. The response is not cacheable. */
        post: operations["loginWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revoke the resolved current session and clear the cookie. A valid session requires its X-CSRF-Token header and a trusted same-origin Origin. Absent or invalid sessions may clear the cookie without a CSRF token, but Origin is still required. The response is not cacheable. */
        post: operations["logoutCurrentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read-only proof of the instance.manage capability. Each request resolves the current session and active global role before authorization. No Administration mutation is exposed. */
        get: operations["getAdministratorStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthoringMemberAddRequest: {
            expectedDraftRevision: number;
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            role: "AUTHOR" | "MAINTAINER";
        };
        AuthoringMemberRoleRequest: {
            expectedDraftRevision: number;
            /** @enum {string} */
            role: "AUTHOR" | "MAINTAINER";
        };
        AuthoringMemberRevokeRequest: {
            expectedDraftRevision: number;
        };
        AuthoringMemberMutationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            role: "AUTHOR" | "MAINTAINER";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt?: string | null;
            draftRevision: number;
        };
        AuthoringLessonCreateRequest: {
            expectedDraftRevision: number;
            stableKey: string;
            title: string;
            description: string;
            objectives: string[];
            estimatedDurationMinutes?: number | null;
            position: number;
        };
        AuthoringLessonUpdateRequest: {
            expectedLessonRevision: number;
            title?: string;
            description?: string;
            objectives?: string[];
            estimatedDurationMinutes?: number | null;
        };
        AuthoringLessonOrderModule: {
            /** Format: uuid */
            moduleId: string;
            lessonIds: string[];
        };
        AuthoringLessonReorderRequest: {
            expectedDraftRevision: number;
            modules: components["schemas"]["AuthoringLessonOrderModule"][];
        };
        AuthoringLessonPrerequisitesRequest: {
            expectedLessonRevision: number;
            prerequisiteLessonKeys: string[];
        };
        AuthoringLessonDeleteRequest: {
            expectedDraftRevision: number;
            expectedLessonRevision: number;
        };
        AuthoringLessonContentUpdateRequest: {
            expectedLessonRevision: number;
            content: components["schemas"]["LessonContent"];
        };
        AuthoringLessonContentMutationResponse: {
            lesson: components["schemas"]["AuthoringLessonMutationResponse"];
            content: components["schemas"]["LessonContent"];
        };
        AuthoringLessonMutationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            draft_id: string;
            /** Format: uuid */
            module_id: string;
            stable_key: string;
            title: string;
            description: string;
            objectives: string[];
            estimated_duration_minutes: number | null;
            position: number;
            revision: number;
            draftRevision: number;
        };
        AuthoringModuleCreateRequest: {
            expectedDraftRevision: number;
            stableKey: string;
            title: string;
            description?: string;
            position: number;
        };
        AuthoringModuleUpdateRequest: {
            expectedModuleRevision: number;
            title?: string;
            description?: string;
        };
        AuthoringModuleReorderRequest: {
            expectedDraftRevision: number;
            moduleIds: string[];
        };
        AuthoringModuleDeleteRequest: {
            expectedDraftRevision: number;
            expectedModuleRevision: number;
        };
        AuthoringModuleMutationResponse: {
            module: components["schemas"]["AuthoringModuleSummary"];
            draftRevision: number;
        };
        AuthoringModuleOrderResponse: {
            draftRevision: number;
        };
        AuthoringDraftUpdateRequest: {
            expectedRevision: number;
            intendedVersion?: string;
            sourceLanguage?: string;
            title?: string;
            description?: string;
            objectives?: string[];
            changelog?: string;
            license?: components["schemas"]["ContentLicense"];
        };
        AuthoringDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            course_id: string;
            intended_version: string;
            source_language: string;
            title: string;
            description: string;
            objectives: string[];
            changelog: string;
            license: components["schemas"]["ContentLicense"];
            /** @enum {string} */
            status: "ACTIVE" | "ABANDONED";
            revision: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuthoringWorkspace: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            draft_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_activity_at: string;
        };
        AuthoringLessonSummary: {
            /** Format: uuid */
            id: string;
            stable_key: string;
            title: string;
            description: string;
            objectives: string[];
            estimated_duration_minutes: number | null;
            position: number;
            revision: number;
            recommended_prerequisite_keys: string[];
        };
        AuthoringModuleSummary: {
            /** Format: uuid */
            id: string;
            stable_key: string;
            title: string;
            description: string;
            position: number;
            revision: number;
            lessons: components["schemas"]["AuthoringLessonSummary"][];
        };
        AuthoringStructure: {
            modules: components["schemas"]["AuthoringModuleSummary"][];
        };
        AuthoringLessonDetail: components["schemas"]["AuthoringLessonSummary"] & {
            /** Format: uuid */
            draft_id: string;
            /** Format: uuid */
            module_id: string;
            content: components["schemas"]["LessonContent"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CourseList: {
            courses: components["schemas"]["CourseSummary"][];
        };
        CourseSummary: {
            slug: string;
            version: components["schemas"]["CourseVersionSummary"];
        };
        CourseIdentity: {
            slug: string;
        };
        CourseDetail: {
            course: components["schemas"]["CourseIdentity"];
            version: components["schemas"]["CourseVersionSummary"];
            modules: components["schemas"]["ModuleStructure"][];
        };
        CourseVersionSummary: {
            version: string;
            /** @enum {string} */
            status: "PUBLISHED" | "DEPRECATED" | "ARCHIVED";
            title: string;
            description: string;
            objectives: string[];
            source_language: string;
            license: components["schemas"]["ContentLicense"];
            contributors: components["schemas"]["Contributor"][];
        };
        Contributor: {
            display_name: string;
            /** @enum {string} */
            role: "AUTHOR" | "MAINTAINER";
            order: number;
        };
        ContentLicense: {
            /** @enum {string} */
            kind: "STANDARD" | "ALL_RIGHTS_RESERVED" | "CUSTOM";
            identifier: string;
            display_name: string;
            /** @description Empty when no public license URL is present. */
            url: string;
            custom_text: string;
        };
        ModuleSummary: {
            key: string;
            title: string;
            description: string;
            position: number;
        };
        LessonSummary: {
            key: string;
            title: string;
            description: string;
            objectives: string[];
            estimated_duration_minutes: number | null;
            position: number;
            recommended_prerequisite_keys: string[];
        };
        ModuleStructure: {
            module: components["schemas"]["ModuleSummary"];
            lessons: components["schemas"]["LessonSummary"][];
        };
        LessonDetail: {
            course: components["schemas"]["CourseIdentity"];
            version: components["schemas"]["CourseVersionSummary"];
            module: components["schemas"]["ModuleSummary"];
            lesson: components["schemas"]["LessonSummary"] & {
                content: components["schemas"]["LessonContent"];
            };
        };
        LessonContent: {
            /** @constant */
            schemaVersion: 1;
            blocks: components["schemas"]["LessonBlock"][];
        };
        LessonBlock: components["schemas"]["TextBlock"] | components["schemas"]["HeadingBlock"] | components["schemas"]["ImageBlock"] | components["schemas"]["VideoBlock"] | components["schemas"]["AudioBlock"] | components["schemas"]["CodeBlock"] | components["schemas"]["QuoteBlock"] | components["schemas"]["CalloutBlock"] | components["schemas"]["TableBlock"] | components["schemas"]["DownloadBlock"] | components["schemas"]["KnowledgeCheckBlock"] | components["schemas"]["DividerBlock"];
        BlockEnvelope: {
            key: string;
            type: string;
        };
        TextBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "TEXT";
            payload: {
                content: components["schemas"]["RichText"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TEXT";
        };
        HeadingBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "HEADING";
            payload: {
                level: number;
                content: components["schemas"]["RichTextInline"][];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HEADING";
        };
        AssetReference: {
            assetKey: string;
        };
        ImageBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "IMAGE";
            payload: {
                asset: components["schemas"]["AssetReference"];
                altText?: string;
                decorative: boolean;
                caption?: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "IMAGE";
        };
        VideoBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "VIDEO";
            payload: {
                asset: components["schemas"]["AssetReference"];
                title: string;
                transcript?: string;
                transcriptAsset?: components["schemas"]["AssetReference"];
                captionsAsset: components["schemas"]["AssetReference"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "VIDEO";
        };
        AudioBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "AUDIO";
            payload: {
                asset: components["schemas"]["AssetReference"];
                title: string;
                transcript?: string;
                transcriptAsset?: components["schemas"]["AssetReference"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "AUDIO";
        };
        CodeBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "CODE";
            payload: {
                code: string;
                language?: string;
                title?: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CODE";
        };
        QuoteBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "QUOTE";
            payload: {
                text: string;
                attribution?: string;
                /** Format: uri-reference */
                sourceUrl?: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "QUOTE";
        };
        CalloutBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "CALLOUT";
            payload: {
                /** @enum {string} */
                kind: "INFO" | "NOTE" | "WARNING" | "TIP";
                title?: string;
                content: components["schemas"]["RichText"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CALLOUT";
        };
        TableBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "TABLE";
            payload: {
                caption?: string;
                headers: string[];
                rows: string[][];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TABLE";
        };
        DownloadBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "DOWNLOAD";
            payload: {
                asset: components["schemas"]["AssetReference"];
                label: string;
                description?: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DOWNLOAD";
        };
        KnowledgeCheckBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "KNOWLEDGE_CHECK";
            payload: {
                assessmentKey: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "KNOWLEDGE_CHECK";
        };
        DividerBlock: components["schemas"]["BlockEnvelope"] & {
            /** @constant */
            type?: "DIVIDER";
            payload: Record<string, never>;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DIVIDER";
        };
        /** @description Constrained semantic rich text. It is not HTML or editor state. */
        RichText: {
            nodes: components["schemas"]["RichTextNode"][];
        };
        RichTextNode: {
            /** @enum {string} */
            type?: "paragraph" | "bullet_list" | "ordered_list";
            content?: components["schemas"]["RichTextInline"][];
            items?: components["schemas"]["RichTextInline"][][];
        };
        RichTextInline: {
            /** @enum {string} */
            type?: "text" | "hard_break";
            text?: string;
            marks?: components["schemas"]["RichTextMark"][];
        };
        RichTextMark: {
            /** @enum {string} */
            type: "emphasis" | "strong" | "inline_code" | "link";
            /** Format: uri-reference */
            href?: string;
        };
        LoginRequest: {
            email: string;
            /** Format: password */
            password: string;
        };
        AuthenticatedSession: {
            /** @constant */
            authenticated: true;
            /** Format: uuid */
            user_id: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Session-bound synchronizer token. Keep in memory and send as X-CSRF-Token on cookie-authenticated POST, PUT, PATCH, and DELETE requests. Not an authentication credential. */
            csrf_token: string;
        };
        AdminStatus: {
            /** @constant */
            status: "ok";
        };
        Health: {
            status: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            instance: string;
            request_id: string;
        };
    };
    responses: {
        /** @description RFC 9457 Problem Details with request correlation ID */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AuthoringDraftID: string;
        AuthoringUserID: string;
        AuthoringModuleID: string;
        AuthoringLessonID: string;
        CourseSlug: string;
        CourseVersion: string;
        LessonKey: string;
        /** @description Required when a valid btg_session cookie is present. Use the csrf_token from a no-store login or current-session response. This token is not an authentication credential. */
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthoringDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft metadata and current revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringDraft"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    updateAuthoringDraftMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringDraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Committed updated draft metadata with incremented revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringDraft"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getAuthoringWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private workspace metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringWorkspace"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    createAuthoringModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringModuleCreateRequest"];
            };
        };
        responses: {
            /** @description Committed Module and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringModuleMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    addAuthoringMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringMemberAddRequest"];
            };
        };
        responses: {
            /** @description Committed membership and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringMemberMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    revokeAuthoringMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                userId: components["parameters"]["AuthoringUserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringMemberRevokeRequest"];
            };
        };
        responses: {
            /** @description Revoked membership and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringMemberMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    changeAuthoringMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                userId: components["parameters"]["AuthoringUserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringMemberRoleRequest"];
            };
        };
        responses: {
            /** @description Committed active membership and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringMemberMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    reorderAuthoringModules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringModuleReorderRequest"];
            };
        };
        responses: {
            /** @description Committed Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringModuleOrderResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    deleteAuthoringModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                moduleId: components["parameters"]["AuthoringModuleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringModuleDeleteRequest"];
            };
        };
        responses: {
            /** @description Committed Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringModuleOrderResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    updateAuthoringModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                moduleId: components["parameters"]["AuthoringModuleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringModuleUpdateRequest"];
            };
        };
        responses: {
            /** @description Committed Module and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringModuleMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    createAuthoringLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                moduleId: components["parameters"]["AuthoringModuleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringLessonCreateRequest"];
            };
        };
        responses: {
            /** @description Committed Lesson metadata and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringLessonMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    reorderAuthoringLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringLessonReorderRequest"];
            };
        };
        responses: {
            /** @description Committed Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringModuleOrderResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getAuthoringLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                lessonId: components["parameters"]["AuthoringLessonID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private draft lesson with canonical semantic content and current revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringLessonDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    deleteAuthoringLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                lessonId: components["parameters"]["AuthoringLessonID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringLessonDeleteRequest"];
            };
        };
        responses: {
            /** @description Committed Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringModuleOrderResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    updateAuthoringLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                lessonId: components["parameters"]["AuthoringLessonID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringLessonUpdateRequest"];
            };
        };
        responses: {
            /** @description Committed Lesson metadata and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringLessonMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    replaceAuthoringLessonPrerequisites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                lessonId: components["parameters"]["AuthoringLessonID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringLessonPrerequisitesRequest"];
            };
        };
        responses: {
            /** @description Committed Lesson metadata and current Draft revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringLessonMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    replaceAuthoringLessonContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
                lessonId: components["parameters"]["AuthoringLessonID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringLessonContentUpdateRequest"];
            };
        };
        responses: {
            /** @description Committed canonical content and current Lesson and Draft revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringLessonContentMutationResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getAuthoringDraftStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["AuthoringDraftID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered modules and lesson summaries without full lesson content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthoringStructure"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    listPublishedCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discoverable courses and preferred published versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseList"];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    getCurrentCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["CourseSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preferred published course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getCourseVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["CourseSlug"];
                version: components["parameters"]["CourseVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Explicit servable historical or published version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getPublishedLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["CourseSlug"];
                version: components["parameters"]["CourseVersion"];
                lessonKey: components["parameters"]["LessonKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical published lesson content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    loginWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; opaque token is returned only in the Set-Cookie header */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedSession"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            /** @description Source login rate exceeded or authentication work saturated. Retry-After is provided when source refill time is known. */
            429: {
                headers: {
                    /** @description Whole seconds until the source bucket can admit another attempt; absent for other admission failures. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    logoutCurrentSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when a valid btg_session cookie is present. Use the csrf_token from a no-store login or current-session response. This token is not an authentication credential. */
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out; session cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated session and its synchronizer CSRF token; response is not cacheable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedSession"];
                };
            };
            401: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getAdministratorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor may manage the instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatus"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Critical dependencies and schema are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
