// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authoring.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonDraft = `-- name: AbandonDraft :one
UPDATE authoring.course_draft
SET status = 'ABANDONED', revision = revision + 1, updated_at = now()
WHERE id = $1 AND revision = $2 AND status = 'ACTIVE'
RETURNING id, course_id, intended_version, source_language, title, description, learning_objectives, changelog, license, status, revision, created_at, updated_at
`

type AbandonDraftParams struct {
	ID       pgtype.UUID
	Revision int64
}

func (q *Queries) AbandonDraft(ctx context.Context, arg AbandonDraftParams) (AuthoringCourseDraft, error) {
	row := q.db.QueryRow(ctx, abandonDraft, arg.ID, arg.Revision)
	var i AuthoringCourseDraft
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.IntendedVersion,
		&i.SourceLanguage,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.Changelog,
		&i.License,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const activeMembershipForDraft = `-- name: ActiveMembershipForDraft :one
SELECT member.role
FROM authoring.workspace_member AS member
JOIN authoring.workspace AS workspace ON workspace.id = member.workspace_id
WHERE workspace.draft_id = $1 AND member.user_id = $2 AND member.revoked_at IS NULL
`

type ActiveMembershipForDraftParams struct {
	DraftID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) ActiveMembershipForDraft(ctx context.Context, arg ActiveMembershipForDraftParams) (string, error) {
	row := q.db.QueryRow(ctx, activeMembershipForDraft, arg.DraftID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const addMember = `-- name: AddMember :one
INSERT INTO authoring.workspace_member (workspace_id, user_id, role)
SELECT $1, $2, $3 FROM authoring.workspace AS w
JOIN authoring.course_draft AS d ON d.id = w.draft_id
WHERE w.id = $1 AND d.status = 'ACTIVE'
RETURNING id, workspace_id, user_id, role, created_at, revoked_at
`

type AddMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (AuthoringWorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i AuthoringWorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const addPrerequisite = `-- name: AddPrerequisite :exec
INSERT INTO authoring.lesson_prerequisite (draft_id, lesson_id, prerequisite_lesson_id, position)
VALUES ($1, $2, $3, $4)
`

type AddPrerequisiteParams struct {
	DraftID              pgtype.UUID
	LessonID             pgtype.UUID
	PrerequisiteLessonID pgtype.UUID
	Position             int32
}

func (q *Queries) AddPrerequisite(ctx context.Context, arg AddPrerequisiteParams) error {
	_, err := q.db.Exec(ctx, addPrerequisite,
		arg.DraftID,
		arg.LessonID,
		arg.PrerequisiteLessonID,
		arg.Position,
	)
	return err
}

const bumpDraftRevision = `-- name: BumpDraftRevision :one
UPDATE authoring.course_draft
SET revision = revision + 1, updated_at = now()
WHERE id = $1 AND revision = $2 AND status = 'ACTIVE'
RETURNING id, course_id, intended_version, source_language, title, description, learning_objectives, changelog, license, status, revision, created_at, updated_at
`

type BumpDraftRevisionParams struct {
	ID       pgtype.UUID
	Revision int64
}

func (q *Queries) BumpDraftRevision(ctx context.Context, arg BumpDraftRevisionParams) (AuthoringCourseDraft, error) {
	row := q.db.QueryRow(ctx, bumpDraftRevision, arg.ID, arg.Revision)
	var i AuthoringCourseDraft
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.IntendedVersion,
		&i.SourceLanguage,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.Changelog,
		&i.License,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bumpLessonRevision = `-- name: BumpLessonRevision :one
UPDATE authoring.lesson AS l SET revision = l.revision + 1, updated_at = now()
WHERE l.id = $1 AND l.revision = $2
  AND EXISTS (SELECT 1 FROM authoring.course_draft AS d WHERE d.id = l.draft_id AND d.status = 'ACTIVE')
RETURNING l.id, l.draft_id, l.module_id, l.stable_key, l.title, l.description, l.learning_objectives, l.estimated_duration_minutes, l.position, l.content, l.revision, l.created_at, l.updated_at
`

type BumpLessonRevisionParams struct {
	ID       pgtype.UUID
	Revision int64
}

func (q *Queries) BumpLessonRevision(ctx context.Context, arg BumpLessonRevisionParams) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, bumpLessonRevision, arg.ID, arg.Revision)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bumpModuleRevision = `-- name: BumpModuleRevision :one
UPDATE authoring.module AS m SET revision = m.revision + 1, updated_at = now()
WHERE m.id = $1 AND m.revision = $2
  AND EXISTS (SELECT 1 FROM authoring.course_draft AS d WHERE d.id = m.draft_id AND d.status = 'ACTIVE')
RETURNING m.id, m.draft_id, m.stable_key, m.title, m.description, m.position, m.revision, m.created_at, m.updated_at
`

type BumpModuleRevisionParams struct {
	ID       pgtype.UUID
	Revision int64
}

func (q *Queries) BumpModuleRevision(ctx context.Context, arg BumpModuleRevisionParams) (AuthoringModule, error) {
	row := q.db.QueryRow(ctx, bumpModuleRevision, arg.ID, arg.Revision)
	var i AuthoringModule
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDraft = `-- name: CreateDraft :one
INSERT INTO authoring.course_draft (course_id, intended_version, source_language, title, description, learning_objectives, changelog, license)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, course_id, intended_version, source_language, title, description, learning_objectives, changelog, license, status, revision, created_at, updated_at
`

type CreateDraftParams struct {
	CourseID           pgtype.UUID
	IntendedVersion    string
	SourceLanguage     string
	Title              string
	Description        string
	LearningObjectives []byte
	Changelog          string
	License            []byte
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (AuthoringCourseDraft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.CourseID,
		arg.IntendedVersion,
		arg.SourceLanguage,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.Changelog,
		arg.License,
	)
	var i AuthoringCourseDraft
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.IntendedVersion,
		&i.SourceLanguage,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.Changelog,
		&i.License,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO authoring.lesson (draft_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, content)
SELECT m.draft_id, m.id, $2, $3, $4, $5, $6, $7, $8
FROM authoring.module AS m
JOIN authoring.course_draft AS d ON d.id = m.draft_id
WHERE m.id = $1 AND m.draft_id = $9 AND d.status = 'ACTIVE'
RETURNING id, draft_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, content, revision, created_at, updated_at
`

type CreateLessonParams struct {
	ID                       pgtype.UUID
	StableKey                string
	Title                    string
	Description              string
	LearningObjectives       []byte
	EstimatedDurationMinutes pgtype.Int4
	Position                 int32
	Content                  []byte
	DraftID                  pgtype.UUID
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.ID,
		arg.StableKey,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.EstimatedDurationMinutes,
		arg.Position,
		arg.Content,
		arg.DraftID,
	)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModule = `-- name: CreateModule :one
INSERT INTO authoring.module (draft_id, stable_key, title, description, position)
SELECT d.id, $2, $3, $4, $5 FROM authoring.course_draft AS d
WHERE d.id = $1 AND d.status = 'ACTIVE'
RETURNING id, draft_id, stable_key, title, description, position, revision, created_at, updated_at
`

type CreateModuleParams struct {
	ID          pgtype.UUID
	StableKey   string
	Title       string
	Description string
	Position    int32
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (AuthoringModule, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.ID,
		arg.StableKey,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i AuthoringModule
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO authoring.workspace (draft_id, created_by_user_id)
VALUES ($1, $2) RETURNING id, draft_id, created_by_user_id, created_at, last_activity_at
`

type CreateWorkspaceParams struct {
	DraftID         pgtype.UUID
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (AuthoringWorkspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.DraftID, arg.CreatedByUserID)
	var i AuthoringWorkspace
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const deleteLesson = `-- name: DeleteLesson :one
DELETE FROM authoring.lesson AS l
WHERE l.id = $1 AND l.revision = $2
  AND EXISTS (SELECT 1 FROM authoring.course_draft AS d WHERE d.id = l.draft_id AND d.status = 'ACTIVE')
RETURNING l.id
`

type DeleteLessonParams struct {
	ID       pgtype.UUID
	Revision int64
}

func (q *Queries) DeleteLesson(ctx context.Context, arg DeleteLessonParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteLesson, arg.ID, arg.Revision)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteModule = `-- name: DeleteModule :one
DELETE FROM authoring.module AS m
WHERE m.id = $1 AND m.revision = $2
  AND EXISTS (SELECT 1 FROM authoring.course_draft AS d WHERE d.id = m.draft_id AND d.status = 'ACTIVE')
RETURNING m.id
`

type DeleteModuleParams struct {
	ID       pgtype.UUID
	Revision int64
}

func (q *Queries) DeleteModule(ctx context.Context, arg DeleteModuleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteModule, arg.ID, arg.Revision)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePrerequisites = `-- name: DeletePrerequisites :exec
DELETE FROM authoring.lesson_prerequisite WHERE lesson_id = $1
`

func (q *Queries) DeletePrerequisites(ctx context.Context, lessonID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePrerequisites, lessonID)
	return err
}

const findLessonByDraftAndKey = `-- name: FindLessonByDraftAndKey :one
SELECT id, draft_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, content, revision, created_at, updated_at FROM authoring.lesson WHERE draft_id = $1 AND stable_key = $2
`

type FindLessonByDraftAndKeyParams struct {
	DraftID   pgtype.UUID
	StableKey string
}

func (q *Queries) FindLessonByDraftAndKey(ctx context.Context, arg FindLessonByDraftAndKeyParams) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, findLessonByDraftAndKey, arg.DraftID, arg.StableKey)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraft = `-- name: GetDraft :one
SELECT id, course_id, intended_version, source_language, title, description, learning_objectives, changelog, license, status, revision, created_at, updated_at FROM authoring.course_draft WHERE id = $1
`

func (q *Queries) GetDraft(ctx context.Context, id pgtype.UUID) (AuthoringCourseDraft, error) {
	row := q.db.QueryRow(ctx, getDraft, id)
	var i AuthoringCourseDraft
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.IntendedVersion,
		&i.SourceLanguage,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.Changelog,
		&i.License,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLesson = `-- name: GetLesson :one
SELECT id, draft_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, content, revision, created_at, updated_at FROM authoring.lesson WHERE id = $1
`

func (q *Queries) GetLesson(ctx context.Context, id pgtype.UUID) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModule = `-- name: GetModule :one
SELECT id, draft_id, stable_key, title, description, position, revision, created_at, updated_at FROM authoring.module WHERE id = $1
`

func (q *Queries) GetModule(ctx context.Context, id pgtype.UUID) (AuthoringModule, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i AuthoringModule
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, draft_id, created_by_user_id, created_at, last_activity_at FROM authoring.workspace WHERE draft_id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, draftID pgtype.UUID) (AuthoringWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, draftID)
	var i AuthoringWorkspace
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const listLessons = `-- name: ListLessons :many
SELECT id, draft_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, content, revision, created_at, updated_at FROM authoring.lesson WHERE module_id = $1 ORDER BY position, id
`

func (q *Queries) ListLessons(ctx context.Context, moduleID pgtype.UUID) ([]AuthoringLesson, error) {
	rows, err := q.db.Query(ctx, listLessons, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthoringLesson
	for rows.Next() {
		var i AuthoringLesson
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.ModuleID,
			&i.StableKey,
			&i.Title,
			&i.Description,
			&i.LearningObjectives,
			&i.EstimatedDurationMinutes,
			&i.Position,
			&i.Content,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, workspace_id, user_id, role, created_at, revoked_at FROM authoring.workspace_member WHERE workspace_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListMembers(ctx context.Context, workspaceID pgtype.UUID) ([]AuthoringWorkspaceMember, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthoringWorkspaceMember
	for rows.Next() {
		var i AuthoringWorkspaceMember
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT id, draft_id, stable_key, title, description, position, revision, created_at, updated_at FROM authoring.module WHERE draft_id = $1 ORDER BY position, id
`

func (q *Queries) ListModules(ctx context.Context, draftID pgtype.UUID) ([]AuthoringModule, error) {
	rows, err := q.db.Query(ctx, listModules, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthoringModule
	for rows.Next() {
		var i AuthoringModule
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.StableKey,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrerequisites = `-- name: ListPrerequisites :many
SELECT p.lesson_id, p.prerequisite_lesson_id, p.position, target.stable_key AS target_stable_key
FROM authoring.lesson_prerequisite AS p
JOIN authoring.lesson AS target ON target.id = p.prerequisite_lesson_id
WHERE p.lesson_id = $1 ORDER BY p.position, p.prerequisite_lesson_id
`

type ListPrerequisitesRow struct {
	LessonID             pgtype.UUID
	PrerequisiteLessonID pgtype.UUID
	Position             int32
	TargetStableKey      string
}

func (q *Queries) ListPrerequisites(ctx context.Context, lessonID pgtype.UUID) ([]ListPrerequisitesRow, error) {
	rows, err := q.db.Query(ctx, listPrerequisites, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrerequisitesRow
	for rows.Next() {
		var i ListPrerequisitesRow
		if err := rows.Scan(
			&i.LessonID,
			&i.PrerequisiteLessonID,
			&i.Position,
			&i.TargetStableKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMember = `-- name: RevokeMember :one
UPDATE authoring.workspace_member
SET revoked_at = now()
WHERE workspace_id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, workspace_id, user_id, role, created_at, revoked_at
`

type RevokeMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) RevokeMember(ctx context.Context, arg RevokeMemberParams) (AuthoringWorkspaceMember, error) {
	row := q.db.QueryRow(ctx, revokeMember, arg.WorkspaceID, arg.UserID)
	var i AuthoringWorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const setLessonModuleAndPosition = `-- name: SetLessonModuleAndPosition :one
UPDATE authoring.lesson SET module_id = $2, position = $3, revision = revision + 1, updated_at = now()
WHERE id = $1 AND revision = $4 RETURNING id, draft_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, content, revision, created_at, updated_at
`

type SetLessonModuleAndPositionParams struct {
	ID       pgtype.UUID
	ModuleID pgtype.UUID
	Position int32
	Revision int64
}

func (q *Queries) SetLessonModuleAndPosition(ctx context.Context, arg SetLessonModuleAndPositionParams) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, setLessonModuleAndPosition,
		arg.ID,
		arg.ModuleID,
		arg.Position,
		arg.Revision,
	)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLessonPosition = `-- name: SetLessonPosition :one
UPDATE authoring.lesson SET position = $2, revision = revision + 1, updated_at = now()
WHERE id = $1 RETURNING id, draft_id, module_id, stable_key, title, description, learning_objectives, estimated_duration_minutes, position, content, revision, created_at, updated_at
`

type SetLessonPositionParams struct {
	ID       pgtype.UUID
	Position int32
}

func (q *Queries) SetLessonPosition(ctx context.Context, arg SetLessonPositionParams) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, setLessonPosition, arg.ID, arg.Position)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setModulePosition = `-- name: SetModulePosition :one
UPDATE authoring.module
SET position = $2, revision = revision + 1, updated_at = now()
WHERE id = $1 RETURNING id, draft_id, stable_key, title, description, position, revision, created_at, updated_at
`

type SetModulePositionParams struct {
	ID       pgtype.UUID
	Position int32
}

func (q *Queries) SetModulePosition(ctx context.Context, arg SetModulePositionParams) (AuthoringModule, error) {
	row := q.db.QueryRow(ctx, setModulePosition, arg.ID, arg.Position)
	var i AuthoringModule
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchDraft = `-- name: TouchDraft :exec
UPDATE authoring.course_draft SET revision = revision + 1, updated_at = now()
WHERE id = $1 AND status = 'ACTIVE'
`

func (q *Queries) TouchDraft(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchDraft, id)
	return err
}

const touchWorkspace = `-- name: TouchWorkspace :exec
UPDATE authoring.workspace SET last_activity_at = now() WHERE draft_id = $1
`

func (q *Queries) TouchWorkspace(ctx context.Context, draftID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchWorkspace, draftID)
	return err
}

const updateDraftMetadata = `-- name: UpdateDraftMetadata :one
UPDATE authoring.course_draft
SET intended_version = $3, source_language = $4, title = $5, description = $6,
    learning_objectives = $7, changelog = $8, license = $9,
    revision = revision + 1, updated_at = now()
WHERE id = $1 AND revision = $2 AND status = 'ACTIVE'
RETURNING id, course_id, intended_version, source_language, title, description, learning_objectives, changelog, license, status, revision, created_at, updated_at
`

type UpdateDraftMetadataParams struct {
	ID                 pgtype.UUID
	Revision           int64
	IntendedVersion    string
	SourceLanguage     string
	Title              string
	Description        string
	LearningObjectives []byte
	Changelog          string
	License            []byte
}

func (q *Queries) UpdateDraftMetadata(ctx context.Context, arg UpdateDraftMetadataParams) (AuthoringCourseDraft, error) {
	row := q.db.QueryRow(ctx, updateDraftMetadata,
		arg.ID,
		arg.Revision,
		arg.IntendedVersion,
		arg.SourceLanguage,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.Changelog,
		arg.License,
	)
	var i AuthoringCourseDraft
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.IntendedVersion,
		&i.SourceLanguage,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.Changelog,
		&i.License,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonContent = `-- name: UpdateLessonContent :one
UPDATE authoring.lesson AS l
SET content = $3, revision = l.revision + 1, updated_at = now()
WHERE l.id = $1 AND l.revision = $2
  AND EXISTS (SELECT 1 FROM authoring.course_draft AS d WHERE d.id = l.draft_id AND d.status = 'ACTIVE')
RETURNING l.id, l.draft_id, l.module_id, l.stable_key, l.title, l.description, l.learning_objectives, l.estimated_duration_minutes, l.position, l.content, l.revision, l.created_at, l.updated_at
`

type UpdateLessonContentParams struct {
	ID       pgtype.UUID
	Revision int64
	Content  []byte
}

func (q *Queries) UpdateLessonContent(ctx context.Context, arg UpdateLessonContentParams) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, updateLessonContent, arg.ID, arg.Revision, arg.Content)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonMetadata = `-- name: UpdateLessonMetadata :one
UPDATE authoring.lesson AS l
SET title = $3, description = $4, learning_objectives = $5, estimated_duration_minutes = $6,
    revision = l.revision + 1, updated_at = now()
WHERE l.id = $1 AND l.revision = $2
  AND EXISTS (SELECT 1 FROM authoring.course_draft AS d WHERE d.id = l.draft_id AND d.status = 'ACTIVE')
RETURNING l.id, l.draft_id, l.module_id, l.stable_key, l.title, l.description, l.learning_objectives, l.estimated_duration_minutes, l.position, l.content, l.revision, l.created_at, l.updated_at
`

type UpdateLessonMetadataParams struct {
	ID                       pgtype.UUID
	Revision                 int64
	Title                    string
	Description              string
	LearningObjectives       []byte
	EstimatedDurationMinutes pgtype.Int4
}

func (q *Queries) UpdateLessonMetadata(ctx context.Context, arg UpdateLessonMetadataParams) (AuthoringLesson, error) {
	row := q.db.QueryRow(ctx, updateLessonMetadata,
		arg.ID,
		arg.Revision,
		arg.Title,
		arg.Description,
		arg.LearningObjectives,
		arg.EstimatedDurationMinutes,
	)
	var i AuthoringLesson
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.ModuleID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.LearningObjectives,
		&i.EstimatedDurationMinutes,
		&i.Position,
		&i.Content,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModule = `-- name: UpdateModule :one
UPDATE authoring.module AS m
SET title = $3, description = $4, revision = m.revision + 1, updated_at = now()
WHERE m.id = $1 AND m.revision = $2
  AND EXISTS (SELECT 1 FROM authoring.course_draft AS d WHERE d.id = m.draft_id AND d.status = 'ACTIVE')
RETURNING m.id, m.draft_id, m.stable_key, m.title, m.description, m.position, m.revision, m.created_at, m.updated_at
`

type UpdateModuleParams struct {
	ID          pgtype.UUID
	Revision    int64
	Title       string
	Description string
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (AuthoringModule, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.ID,
		arg.Revision,
		arg.Title,
		arg.Description,
	)
	var i AuthoringModule
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.StableKey,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
