// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthoringCourseDraft struct {
	ID                 pgtype.UUID
	CourseID           pgtype.UUID
	IntendedVersion    string
	SourceLanguage     string
	Title              string
	Description        string
	LearningObjectives []byte
	Changelog          string
	License            []byte
	Status             string
	Revision           int64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AuthoringLesson struct {
	ID                       pgtype.UUID
	DraftID                  pgtype.UUID
	ModuleID                 pgtype.UUID
	StableKey                string
	Title                    string
	Description              string
	LearningObjectives       []byte
	EstimatedDurationMinutes pgtype.Int4
	Position                 int32
	Content                  []byte
	Revision                 int64
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type AuthoringLessonPrerequisite struct {
	DraftID              pgtype.UUID
	LessonID             pgtype.UUID
	PrerequisiteLessonID pgtype.UUID
	Position             int32
}

type AuthoringModule struct {
	ID          pgtype.UUID
	DraftID     pgtype.UUID
	StableKey   string
	Title       string
	Description string
	Position    int32
	Revision    int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AuthoringReviewCycle struct {
	ID                    pgtype.UUID
	DraftID               pgtype.UUID
	DraftRevision         int64
	SnapshotSchemaVersion int32
	Snapshot              []byte
	Status                string
	Revision              int64
	SubmittedByUserID     pgtype.UUID
	SubmittedAt           pgtype.Timestamptz
	DecidedByUserID       pgtype.UUID
	DecidedAt             pgtype.Timestamptz
}

type AuthoringReviewEvent struct {
	ID          pgtype.UUID
	ReviewID    pgtype.UUID
	EventType   string
	ActorUserID pgtype.UUID
	Message     pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type AuthoringReviewPublication struct {
	ReviewID          pgtype.UUID
	ReviewRevision    int64
	DraftID           pgtype.UUID
	DraftRevision     int64
	CourseID          pgtype.UUID
	CourseVersion     string
	CourseVersionID   pgtype.UUID
	PublishedAt       pgtype.Timestamptz
	PublishedByUserID pgtype.UUID
	RecordedAt        pgtype.Timestamptz
}

type AuthoringWorkspace struct {
	ID              pgtype.UUID
	DraftID         pgtype.UUID
	CreatedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	LastActivityAt  pgtype.Timestamptz
}

type AuthoringWorkspaceMember struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type CoursesCourse struct {
	ID        pgtype.UUID
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type CoursesCourseVersion struct {
	ID                 pgtype.UUID
	CourseID           pgtype.UUID
	Version            string
	VersionMajor       pgtype.Int4
	VersionMinor       pgtype.Int4
	VersionPatch       pgtype.Int4
	Status             string
	Title              string
	Description        string
	LearningObjectives []byte
	SourceLanguage     string
	Changelog          string
	LicenseKind        string
	LicenseIdentifier  pgtype.Text
	LicenseDisplayName string
	LicenseUrl         pgtype.Text
	LicenseCustomText  pgtype.Text
	Attribution        []byte
	CreatedAt          pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
}
