import { apiClient, type APIClient } from '../api/client'
import type { components } from '../api/generated'
import { InvalidCourseRouteError, InvalidPublishedCourseResponseError, isCourseVersion, isPublishedCourseID } from './courses'
export type LearnerCertificate=components['schemas']['LearnerCertificate']; export type PublicCertificate=components['schemas']['PublicCertificate']
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
export function certificatePath(id:string){return `/certificates/${encodeURIComponent(id)}`};export function verificationPath(id:string){return `/verify/certificates/${encodeURIComponent(id)}`}
export async function issueCertificate(courseId:string,version:string,client:APIClient=apiClient):Promise<LearnerCertificate>{if(!isPublishedCourseID(courseId)||!isCourseVersion(version))throw new InvalidCourseRouteError();return validate(await client.request<unknown>(`/api/courses/by-id/${encodeURIComponent(courseId)}/versions/${encodeURIComponent(version)}/certificate`,{method:'POST',cache:'no-store'}),true)}
export async function getLearnerCertificate(id:string,client:APIClient=apiClient):Promise<LearnerCertificate>{if(!uuid.test(id))throw new InvalidCourseRouteError();return validate(await client.request<unknown>(`/api/learner/certificates/${encodeURIComponent(id)}`,{cache:'no-store'}),true)}
export async function getPublicCertificate(id:string,client:APIClient=apiClient):Promise<PublicCertificate>{if(!uuid.test(id))throw new InvalidCourseRouteError();return validate(await client.request<unknown>(`/api/public/certificates/${encodeURIComponent(id)}`,{cache:'no-store'}),false)}
function validate(v:unknown,privateView:boolean):any{if(!record(v)||!uuid.test(String(v.certificateId))||!['ACTIVE','REVOKED'].includes(String(v.status))||!date(v.issuedAt)||!(v.revokedAt===null||date(v.revokedAt))||!achievement(v.achievement)||!issuer(v.issuer)||privateView!==Object.hasOwn(v,'verificationPath')||(privateView&&typeof v.verificationPath!=='string'))throw new InvalidPublishedCourseResponseError();return v}
function achievement(v:unknown){return record(v)&&only(v,['courseId','title','version','language','criteria'])&&isPublishedCourseID(String(v.courseId))&&text(v.title,240)&&isCourseVersion(String(v.version))&&text(v.language,64)&&text(v.criteria,4000)}function issuer(v:unknown){return record(v)&&only(v,['id','name'])&&text(v.id,256)&&text(v.name,256)}function record(v:unknown):v is Record<string,any>{return typeof v==='object'&&v!==null&&!Array.isArray(v)}function only(v:Record<string,any>,keys:string[]){return Object.keys(v).every(k=>keys.includes(k))}function text(v:unknown,n:number){return typeof v==='string'&&v.trim()===v&&v.length>0&&v.length<=n}function date(v:unknown){return typeof v==='string'&&!Number.isNaN(Date.parse(v))}
